### ISSUE TITLE
Improve user experience for subkey feature

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#1108]
## User Story
As Chris, I want to understand the difference between connecting to the LC using the subkey account and my main account and have a seamless interaction between accounts.

## Acceptance criteria
Now when we have a basic dApp implementation of the subkey or next step should be to improve the user experience for this feature.
* The user understands the relationship between both options.
* The user can transfer small amounts of ETH and tokens between subkey account and main account.
* The user can see her ETH and token balance for both accounts.
* Possibility for the user to choose which account to use for on-chain operations.

This is an continouation of isse #745.

## Tasks
- [ ] Split the issue

**Comment by christianbrb** [comment]
### Collecting some information
#### Overview / Flow
![Derived subkey diagram](https://user-images.githubusercontent.com/587021/70165823-4ec0e980-16a2-11ea-9c96-9ca2f38f52f6.png)

#### Thoughts
- Tokens are "transferred" to the Raiden Account (aka subkey/-account) during deposit
- Tokens are going to accumulate within the Raiden Account (aka subkey/-account) when settling channel(s) (or withdraw once implemented)
- The balance of tokens and ETH of the ETH/Main Account are visible within MetaMask (or another wallet)
- The 
- Because of that, I would propose to
    - to just show the balances of the Raiden Account within the dApp
    - to give the user the option to retransfer tokens to the Main Account

**Comment by andrevmatos** [comment]
> to just show the balances of the Raiden Account within the dApp

This could be misleading, because the mainkey balances are the ones available for usage from the subkey (ETH for paying for txs, tokens for depositing), and showing the subkey's will almost always be zero (i.e. not very useful). This is why it was done like that. 
A more explicit alternative is to show the mainkey (useable) balances by default, but with a small dropdown which shows a small menu with a line for the mainkey balance, and another for the subkey's.

> to give the user the option to retransfer tokens to the Main Account

This is indeed needed, and respective methods are already implemented in the SDK:
https://github.com/raiden-network/light-client/blob/16edf09602404f6431a3c0f3dbf162fe86ab59b3/raiden-ts/src/raiden.ts#L1088-L1156
But while https://github.com/raiden-network/raiden-contracts/issues/1123 and https://github.com/raiden-network/raiden-contracts/issues/352 are not implemented, we need to provide dialogs and inform the user of the need to transfer small amounts of ETH to the subkey (can be as low as 0.0001 or something like that, needs to estimate good suggestions) in order to pay for gas for transfering tokens from subkey back to the main account.

**Comment by christianbrb** [comment]
@andrevmatos Thanks for your reply.

For tokens it makes sense and we should just keep the UI as it is right now :)

**Comment by christianbrb** [comment]
Wild idea: Couldn't we wrap raiden-network/raiden-contracts#1123 and raiden-network/raiden-contracts#352 in a new smart contract? Maybe it would also make sense to make settle and close an atomic operation in that new smart contract.

**Comment by christianbrb** [comment]
Removed from the product backlog as we have got split new issues now.

**Comment by christianbrb** [comment]
Closing as we have got individual issues
