### ISSUE TITLE
I want to use locally cached PFS responses

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1260]
## User Story
As Chris, I want to use locally cached PFS responses so that I save tokens and gain performance.

**Comment by kelsos** [comment]
The biggest issue I can see with caching is that the route might become invalid directly after use.

A valid route depends on the liquidity and availability of each hop between the sender and the target. Thus it might be ok if I try to send `x` but if I try to send `2x` if someone doesn't have enough liquidity this route will fail. 

The same goes if the node goes offline, but let's assume that we have a healthy network with high availability nodes.

While I can try the route and see if it fails. If I am not mistaken, the way the protocol currently works, with RefundTransfers being available only with internal routing in the python client, this essentially means that if the tried route is not valid the amount will be locked until `LockExpiry`.

Do we have any way of ensuring that the route is valid the second time other than trying it or asking PFS for a route? Is it acceptable that the amount will be locked for `x` (until LockExpiry) minutes?

Also, in this case, does this transfer stay `pending` until the lock expires? or do we get feedback that it is not possible instantly so we can fall back to requesting a new route? If we have no refund transfer and we have to wait for the lock to expire then this that we cannot instantly retry for a fresh route.

**Comment by nephix** [comment]
At least on https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html I wasn't able to spot an endpoint that we could use to validate a route + amount

**Comment by kelsos** [comment]
Yes, I think the idea is that each time you need to send a mediated transfer you have to ask the pathfinding service.

**Comment by nephix** [comment]
From a consumer perspective I can see that it would make sense in terms of speed and also economically to reuse routes, if possible

**Comment by kelsos** [comment]
Yes, I agree, as a user, I would also like to minimize the cost but at least currently this doesn't seem easy.

**Comment by andrevmatos** [comment]
Add to the issues kelsos mentioned the variable fees algorithm. When we request a route, we send the amount we intend to transfer with it, so PFS can check for an available route and knowing the capacities (updated by nodes with `PFSFeeUpdate`), estimate the needed fee, and we send the transfer with a margin on top of this reported fee so we can have a higher probability that the transfer will succeed. After the first transfer, by definition the charged fees will change, and we can't be sure if down or up, so transfering using the cached route will probably fail.
The best solution for this on the infinite future utopic world would be:
- Reintroduce `fee` field and use an incremental algorithm, when the user can agree and pay for fees upon unlock instead of on transfer, so we don't hard depend on PFS for fees, but it is used only for estimation/sorting of the best route
- @hackaugusto mentioned some algorithm which may allow failing transfers to be refunded immediately (without depending on liquidity for RefundTransfer nor needing to wait for the lock to expire); this would allow a transfer to fail ASAP upon cache usage and a new request to be made

**Comment by christianbrb** [comment]
Nice discussion, thanks :)

The routing will never be deterministic (like the route-finding in GoogleMaps). In a network, routes and capacities might change quickly. Caching needs to be well configured (eg. just for very small payments, just for two hops, just predefined routes, etc.). There are a lot of options. Maybe it also needs additional endpoints in the PFS with more information about the route.

**Comment by eorituz** [comment]
So I agree with a lot of your points.
However, I am convinced that we will have Hubs mediating 90% of all transfers at least in the early -to mid-stage of raiden network.
Therefore I think it is save to assume that the vast majority of routes will go from you through one or two hubs to the target. The Hubs will have a lot of liquidity, since this is there business model. I also assume that the Hubs will provide the cheapest mediation fee.

This leads me to the conclusion that the vast majority of found routs can be reused for at least small to middling size transfers.

I know that a "hub-heavy" network will make the PFS more or less obsolete since finding the route yourself won't be that hard.

Maybe we can agree on sth like "Saving and remembering routes via mediators with high liquidity"?

**Comment by kelsos** [comment]
I am not against the caching idea but we have to solve the "waiting for x until the lock expires" in case a cached route becomes invalid.

**Comment by christianbrb** [comment]
Was a nice idea at that time. Closing as we are not going to implement this soon.
