### ISSUE TITLE
Use WebRTC for faster transfers

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1261]
## Description
Use WebRTC for faster transfers

- Capabilities: advertised using avatar_url
    - Backwards compatible, uses and falls back to current Matrix behavior/protocol
    - No Receive: Fail early sending payments to clients advertising it
    - No Mediate: Fail early mediating through partners advertising it
    - No Delivery: skip signing/sending unneeded Delivered messages
- P2P transport with WebRTC!

- WebRTC channels/protocol, through Matrix, falling back to Room messages
- Works in browser & Node.js, Python lib available
- Actual Matrix VoIP protocol for signaling
    - m.call.invite, m.call.answer, m.call.candidates, m.call.hangup
    - Alleviates burden on Matrix servers by using it mostly for discovery/validation/negotiation/signaling
- P2P, UDP, DTLS (mandatory e2e encryption, native fast)
- Can work with just STUN (including public servers like Google’s) and TURN
    - STUN: P2P, bypass NAT, should work on ~90% of networks, reveals IP/endpoint to peer, fastest
    - Still very limited attack surface, browser-hardened API, strict messages/validation
    - Can use TURN server deployed with Synapse to relay messages if it can’t P2P connect with STUN
    - Can force TURN for privacy (relayed, no p2p), slower than STUN, faster than plain Matrix

![grafik](https://user-images.githubusercontent.com/35398162/78012415-35c10000-7345-11ea-874a-76b7d9018084.png)

![grafik](https://user-images.githubusercontent.com/35398162/78012463-47a2a300-7345-11ea-8bd9-a4ccf7a6f258.png)

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by nephix** [comment]
## Matrix event schemas

* [m.call.answer](https://github.com/matrix-org/matrix-doc/blob/master/event-schemas/examples/m.call.answer)
* [m.call.candidates](https://github.com/matrix-org/matrix-doc/blob/master/event-schemas/examples/m.call.candidates)

**Comment by nephix** [comment]
I have bumped the coverage to 50%

**Comment by christianbrb** [comment]
We should make a release once https://github.com/raiden-network/light-client/pull/1290 is merged. 

@eorituz could test it afterwards with his demo.

**Comment by christianbrb** [comment]
@andrevmatos Is there documentation needed for a developer using this feature?

**Comment by andrevmatos** [comment]
@christianbrb I'm not sure. There's extensive WebRTC documentation available online, and Matrix spec & examples for signaling events is well described too.
Beyond that, we may want to document the implementation details below, for possible reference, but they _should_ be compatible with any client implementing standard/common client with the mentioned upstream protocols & available guides (example: glare detection):
- call_id/channel label/glare detection: the call_id/rtc channel label is a string composed of both end's 0x-prefixed lowercased addresses, lexically sorted and joined with a pipe (`|`). First one (lower address peer) is expected to be the caller, the one who sends the `m.call.invite`; second one is the callee, which waits for the invite and sends the `m.call.answer` (per matrix protocol).
- If they can't establish the channel in some timeout (default=10s), any end can send a `m.call.hangup` to finish the call and retry while the other peer is available on matrix.
- While a channel isn't available (including at startup, or if it can't be established at all) any message request is sent to matrix Room as fallback, and always read from it as well, but connection establishment keeps retrying.
- The channel creation/connection is tried/listened/accepted for whitelisted peers, including partners and nodes for which we've fetched `getAvailability` (like transfer targets), same policy as Room creation/acceptance, but obviously done after it, since room existence is a requirement for matrix signaling protocol.

**Comment by christianbrb** [comment]
@andrevmatos Thanks for the write-up :) If it is not exposed and not affecting the dApp developer there is no need to document it.
