### ISSUE TITLE
path/find/failure: Target doesn't receive transfers

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1291]
While trying to send a mediated transfer to the python client (through hub.raiden.eth) the SDK threw an Error that the target doesn't receive transfers. Has this something to do with the capabilities?

## Steps to Reproduce
1. Serve dApp
2. Connect to hub
3. Launch python client
4. Connect python client to hub
5. Transfer from dApp to python client
6. Try to get a route from the path finding service

## Expected Result
- I get a route and can do the transfer

## Actual Result
<img width="625" alt="Screenshot 2020-04-03 at 11 25 14" src="https://user-images.githubusercontent.com/3169205/78345352-e0336000-759d-11ea-94a6-c87b03f0bd20.png">

## Additional Infos (Optional) 
Logs:
[raiden_2020-04-03T09_19_47.315Z.log](https://github.com/raiden-network/light-client/files/4426131/raiden_2020-04-03T09_19_47.315Z.log)

State:
[raiden_lc_state_2020-04-03T09_26_50.884Z.json.txt](https://github.com/raiden-network/light-client/files/4426153/raiden_lc_state_2020-04-03T09_26_50.884Z.json.txt)

**Comment by andrevmatos** [comment]
This error should NOT happen on normal usage.
Did you switch the account from a light client to the python client?
This error is thrown only if the target has set the capabilities `avatar_url` with `noReceive`:
https://github.com/raiden-network/light-client/blob/a00d4e8ef1ef6bdeb3a7f9c5c969821135aa2378/raiden-ts/src/path/epics.ts#L197-L198

Which is done by the light-client, but never set by the main client, so if you switch an account from light client to python client, it won't be reset and you may get this error, OR you tried to send to a light-client instead of the python client.

**Comment by nephix** [comment]
The transfer was to a python client and it was not changed between LC/python

**Comment by andrevmatos** [comment]
I just checked directly into the matrix server, and your target definitely has these capabilities set, and only the user can set this field, so unless our transport server was hacked and someone explicitly joked on us by setting it there, there **is** or **was** a light-client on your target address, and our light-client did behave properly:
![image](https://user-images.githubusercontent.com/587021/78360716-96427e00-758d-11ea-8942-0b31e58d971b.png)

**Comment by nephix** [comment]
That's very odd, I used dedicated accounts that I only use with my python client docker setup

**Comment by nephix** [comment]
Ok worked with a new account, not sure how they got mixed up. Thanks for looking into it
