### ISSUE TITLE
Errors don't show up in logs

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1292]
Not sure if bug or not, iirc RaidenError was/should be serializable but seems like its not. Would be nice to get the error messages in the logs

## Steps to Reproduce
1. Produce an error, e.g. like in #1291
2. Download logs

## Expected Result
- Error appears in log file

## Actual Result
- `payload: {}`

## Additional Infos (Optional) 
Logs:
[raiden_2020-04-03T09_19_47.315Z.log](https://github.com/raiden-network/light-client/files/4426243/raiden_2020-04-03T09_19_47.315Z.log)

**Comment by andrevmatos** [comment]
Was this on top of 2cf6bf358b481a70ac5b279add62aa5d54f1faab (part of #1245)?
That commit should have fixed this by ensuring we use `stack` for errors.
Thank you for opening this issue, this needs more investigation why that change didn't work here.

**Comment by nephix** [comment]
iirc latest master

**Comment by andrevmatos** [comment]
Hmm, I think I know why it is: that commit only works for `Error`s present directly in the `message` array (args for any logging method). On error actions, the errors are actually the `payload` property ot one of the parameters (the action), that's why they don't get serialized by that fix. Darn.
Anyway, this seems to be an issue only with Firefox, which doesn't know yet how to store Error instances. I'll make a small PR to extend the workaround for those properties as well.
Thanks for the report.

**Comment by nephix** [comment]
> Anyway, this seems to be an issue only with Firefox

I encountered this on Google Chrome

**Comment by andrevmatos** [comment]
Well, weird then, anyway, the fix should work for any browser, by converting errors in payload to their respective `stack` repr. Please, test.

**Comment by andrevmatos** [comment]
This still isn't fixed. See logs in #1651 
We need to look at it again.
