### ISSUE TITLE
I want to transfer tokens back from the Raiden account to the Main account if the partner is settling

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1314]
## User Story
As Chris I want to transfer tokens back from the Raiden account to the Main account if the partner is settling so that I can use them again.

Split from #1301

**Comment by christianbrb** [comment]
My current thoughts for a solution:
- I settle a channel
- If the channel is settled and there are tokens in the Raiden Account, the token is not removed from the transfer screen. Instead of showing address and the amount a button is shown to move the tokens back to the Main account

Drawback:
- It doesn't work if I have got several channels in different states -> brings us back to our 100 point question #571 

Might be sufficient for a solution even if we settle the channel (instead of #1301)

**Comment by christianbrb** [comment]
@andrevmatos Couldn't we use https://docs.openzeppelin.com/learn/sending-gasless-transactions?

The SDK would listen to the settle event and if the Raiden account is the receiver we submit a transaction to the [Gas Station Network](https://gsn.openzeppelin.com/) which the main account is paying.

Looking a little bit deeper into it, it might be not possible or really difficult to implement it (see https://docs.openzeppelin.com/contracts/2.x/gsn-strategies)

_I have not failed. I've just found 10,000 ways that won't work. Thomas A. Edison_

**Comment by christianbrb** [comment]
Maybe it would be easier to expose a specific method for the subkey to
1. Get the current gas price
2. Transfers ETH to the subkey
3. Transfer tokens from the subkey to the main account

 which is called, if the SDK receives the settle event from the blockchain.

It would work for #1301 and this issue.

**Comment by andrevmatos** [comment]
Yes, we could have a method to do it in a single batch, but there's some concerns which could justify we exposing the individual steps. More relevant is that transfer ETH down to the subkey incurs in gas for a transfer, which is the same for the ETH needed for one withdraw or for ten. Therefore, the user may wish to control how much ETH they want to transfer down, planning ahead for a couple of token withdraws, than wasting ETH doing this transfer each time they need to get some tokens back. This difference could even be bigger than the value of the tokens itself. Not sure if it's worth it to care this much, just clarifying that, since the dApp is currently aiming at a more knowledgeable userbase, exposing the full range of operations to the user may be better than trying to "facilitate" things too much but which can end up being wasteful, and then hope that, once we create a simplified UX version for everyday users, the contracts will already support ETH/tokenless accounts (full 3rd-party payers/beneficiaries)

**Comment by christianbrb** [comment]
@andrevmatos Thanks :)

Maybe we just add a separate screen to avoid the hazzle of integrating it too deeply. Let's discuss it in todays planning.

**Comment by christianbrb** [comment]
User flow:
1. Channel is getting closed by the partner
2. Channel is getting settled by the partner
3. Tokens out of channel are transferred from channel to the Raiden account (subkey)
4. Transfer ETH to Raiden Account to pay for gas -> signed in MetaMask (#1365) 
5. Transfer tokens from Raiden Account to Main (ETH) Account -> signed in dApp (background)

Proposed solution:
- Having a button on the general screen for "token balances"
- List of tokens are shown and each token balance can be withdrawn
- Tell the user before settling, that the token balance can be withdrawn on the Account Screen (new naming for General screen)

Question:
- @andrevmatos How does the subkey works for the UDC (SVT tokens)?

**Comment by christianbrb** [comment]
Closing in favor of https://github.com/raiden-network/light-client/issues/1380
