### ISSUE TITLE
I want to mint service tokens on the testnet while connecting to a hub

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1372]
## User Story
As Chris, I want to mint service tokens on the testnet while connecting to a hub so that I am able to deposit it to the UDC.

4 from https://github.com/raiden-network/light-client/issues/1352#issuecomment-615241579

**Comment by kelsos** [comment]
While connecting to a hub sounds a bit broad to me. I am assuming this is only in case you need the channel monitored. Would monitoring be enabled by default, or would the user opt-in to channel monitoring. If there is an opt-in flow I would suggest that we add this functionality to the monitoring opt-in flow, so that we don't do unnecessary actions.

**Comment by christianbrb** [comment]
@kelsos Thanks for your thoughts :)
We'll make receiving and monitoring the default in the dApp.

**Comment by christianbrb** [comment]
I have been writing "while connecting" because I didn't know where exactly to put it. 
After "Open" or after "Deposit". Maybe we should not allow transfers as long as there are no tokens deposited into the UDC contract. We would even need to check if the IOU is still valid to ensure, that monitoring can be paid.

**Comment by christianbrb** [comment]
Will eventually be fixed with #1371
