### ISSUE TITLE
Update dApp connect/onboarding flow

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1373]
## User Story
As Chris I want to see which reward I would pay if a monitoring service submits my balance proof so that I am able to trust the system.

Split from #1352 

## User flow
1. Select Hub (do not show mint & deposit any more)
2. Open Channel (rename to "Set deposit")
3. Monitor Channel (new screen)
3a. Show available SVT tokens (move #1371 to this new screen)
3b. Mint & Deposit button
3c. Show the monitoring reward in SVT
3d. Show the exchange rate (preset but adjustable) -> related SDK feature #1369 
3e. Show the monitoring reward in the channel token = exchange rate * monitoring reward
3f. Explain the monitoring reward briefly
3g. Button should be called "Open Channel" -> not sure if we should call the screen the same

## Acceptance criteria
- Just display the value, how many RDN if the monitoring reward is used. This is not interactive so showing the value is about being transparent about it.
- There is a default for each token we use separated by net
- There is an explanation of how the user can calculate the value

## Tasks
- [ ] Design [Pre-iteration]

**Comment by christianbrb** [comment]
@andrevmatos Proposal: 
- Modal, if we receive a transfer before signing the message for the MS
- Add it to the transfer history

**Comment by christianbrb** [comment]
Please assign the "Ready" label after the design has been done, thanks :)

**Comment by taleldayekh** [comment]
Sure thing!

**Comment by christianbrb** [comment]
@taleldayekh I have written down the user flow (see above). Let me know, if you have got questions.

**Comment by taleldayekh** [comment]
The way I understood this is that we want to be transparent about the amount of SVT/RDN a user might have to spend if a balance proof is sent.

Since this is not interactive (at the moment) I suggest we just add this information on the UDC screen. A user would then see how many SVT/RDN tokens they have and in relation to that also how many of those tokens they need to pay in case a balance proof is sent?
@kelsos @andrevmatos @christianbrb @weilbith

**Comment by christianbrb** [comment]
The original idea was to put it in the token connection flow (see user flow). There it would be more educative / explaining for the user.

**Comment by taleldayekh** [comment]
Alright, let me sit down and continue thinking about this one. I think the issue is a lot bigger than the title suggests.

**Comment by taleldayekh** [comment]
![flowchart_connect](https://user-images.githubusercontent.com/43838780/83246988-2aeae600-a1a3-11ea-9f6a-69bcd98c20c4.jpg)

The token connection flow outlined in the description above would require:
- 3 new screen designs (Select Hub, Set Deposit and Monitor Channel)
- The current implemented connect flow can not be re-used except the `Open Channel` screen because the other screens have elements that either needs to be removed or added.

**Comment by taleldayekh** [comment]
I would like to rename this issue to "Update connect/onboarding flow"? Displaying the monitoring reward is only a minor detail in the scope of this issue.

**Comment by taleldayekh** [comment]
There are also some unknowns/question marks regarding step 3d and step 3e. @andrevmatos could you please leave some comments on those two steps. :)

**Comment by taleldayekh** [comment]
We are pulling this one out from the current iteration after discussions. It's a good idea to look over and re-work the connect flow as outlined in the issue so that it becomes more pedagogical for a user, but for now it is too big and not urgent for mainnet.

We should however add details about the balance proof amount in the newly introduced UDC screen. That information should be added regardless of this issue.

**Comment by andrevmatos** [comment]
> 3\. 3d. Show the exchange rate (preset but adjustable) -> related SDK feature #1369
>     3e. Show the monitoring reward in the channel token = exchange rate * monitoring reward

I'm not sure about this. The exchange rates shouldn't be set by the user, they should be either fetched automatically (#1513) or fallback to some of the stated default behaviors.
Also, the SVT/RDN is our "common currency" to show prices on, and reward is already a config param (defaulting to 5 tokens) on this currency, not sure it'd be worth it to show on the transfer token. We can/could do it for tokens we do have exchange rates, but there may be tokens without it (see fallbacks at the linked issue), but I'm not sure it's useful, because it'd be shown at channel opening time's exchange rate, while the reward could be paid far in the future, when the rate may have changed, so the amount paid by the user in monitoring reward value would have changed in transfer tokens, but is constant in service tokens (5 RDN, unless explictly changed)

**Comment by christianbrb** [comment]
This is a messed up issue ;) Closing.
