### ISSUE TITLE
PFS does not work (unhandled error)

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1388]
## Steps to Reproduce
1. Navigate to https://lightclient.raiden.network/
2. Try to make a mediated transfer to `0x00D8f74a983f4eC1F9D7494E33D03EDc75D0b579` demonode3 through `0x1F916ab5cf1B30B22f24Ebf435f53Ee665344Acf` hub.raiden.network

## Expected Result
- Get a PFS response with a Path

## Actual Result
- Unhandled error appears (see [raiden_2020-04-22T07_03_31.654Z.log](https://github.com/raiden-network/light-client/files/4514343/raiden_2020-04-22T07_03_31.654Z.log))

## Additional Infos (Optional) 
```
- Firefox 75.0
```

**Comment by christianbrb** [comment]
Mediation should go through hub.raiden.network

**Comment by christianbrb** [comment]
Sending a transfer to hub.raiden.network also times out

Maybe related: https://github.com/raiden-network/raiden-hub/issues/11

**Comment by christianbrb** [comment]
Logs for the direct transfer 
[raiden_2020-04-22T07_22_06.344Z.log](https://github.com/raiden-network/light-client/files/4514417/raiden_2020-04-22T07_22_06.344Z.log)

**Comment by kelsos** [comment]
So direct transfers worked for my initially but then failed due to the state of the Raiden node in hub not being persisted. This has been fixed in the deployment configuration https://github.com/raiden-network/ansible/commit/53cbf50cdc0b36415d043f0cdc8197599bfefb14.

Also, the minting and depositing were not working correctly due to a problem with the URL that has been potentially fixed with https://github.com/raiden-network/raiden-hub/pull/23.

I am in the process of closing all the channels from the hub side and opening a new channel with `node1` that had no previous channels to test if things work properly.

**Comment by christianbrb** [comment]
@kelsos You are handling this within the hub repo, right? If not, we should pull this issue into the iteration.

**Comment by kelsos** [comment]
@christianbrb yes, I am looking into the funding code to make sure that it is robust and it can survive errors

**Comment by christianbrb** [comment]
Fixed with a hub issue :) Closing
