### ISSUE TITLE
On-chain operations take a long time to complete

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1418]
## Description
At the moment on-chain operations take a long time to complete. Seen in `Mint and Deposit` and `Open Channel`

CC @nephix 

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
If we can know the average block time and the number of blocks needed for confirmation we could show an approximation of the time needed. We cannot make them faster due to the number of confirmation blocks and block time but we could better inform the user about the time required for this operation.

**Comment by andrevmatos** [comment]
This could be a manifestation of #1434 and fixed by #1475 
Did you experience it again, @nephix ?

**Comment by nephix** [comment]
This was created because in https://drive.google.com/file/d/1ZLgbTgHDUumSx97N_-9IpGqWrDWCCPjl/view the deposit to UDC (without counting minting time into it) took like 2-3mins and I didn't test it since

I didn't experience slow channel opens after the fix in #1475

**Comment by christianbrb** [comment]
@agatsoh Did you experience long on-chain operations during your testing?

**Comment by christianbrb** [comment]
Closing
