### ISSUE TITLE
Document the dApp from a user perspective

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1487]
## Description
Document the dApp from a user perspective

- The right level of documentation has been found. We should not overdo this.
- The difficult topics are explained / FAQed (eg. Raiden Account, settling channels, finding hubs, etc.)

## Acceptance criteria
Same style user documentation as for the [WebUI](https://docs.raiden.network/the-raiden-web-interface/screens)

## Tasks
- [ ] Define relevant sections for LC user documentation
- [ ] Write docs and create gifs for each section

**Comment by christianbrb** [comment]
Meeting notes:
- @weilbith @agatsoh Please add your top 7 questions regarding the dApp to this issue
- Explain the Raiden Account
- Make a tutorial / user guide (without screenshots)
   - Decide on a couple of flows (main flows)
- Where to host it? @christianbrb

**Comment by weilbith** [comment]
Top questions (not sorted by any property):

1. What are the differences and pros/cons for MetaMask versus Raiden account?
2. How do all the service parts work? Why are they necessary? What means monitoring? Where can I get an insight (images?!)?
3. What am I signing there all the time in the dApp when I use the MetaMask account? I see random unicode characters.
4. Why is there a channel overview per token if the dApp only allows to have a single one.
5. Why do I have to sign the same thing again and again each time I access the light client. Why can't it be stored with my state like T&C
6. At which channel do I deposit if I click the `Deposit` button on the main view instead of on the channel directly?
7. How can I trigger my client to scan again for new channels on different token networks?

**Comment by christianbrb** [comment]
Adding an explanation for the sub account ETH

**Comment by agatsoh** [comment]
These are my additions to the questions
1. Whats the difference between the main account and the raiden account ?
2. What is the withdraw  deposit in the UDC screen and withdraw deposit on the channel screen ?
3. why do we need to withdraw service (raiden) tokens before again withdrawing them on the withdraw screen ?
4. Why  do i always get the `Backup State` notification at the bottom ?
5. What is the token balance that i see in the Transfer screen ?
