### ISSUE TITLE
Testing refund transfers

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1488]
## Description
With receiving transfers implemented, refund transfers should also work. Test, if it works, maybe implement an integration test.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
Do refund transfers work anything other than with local routing?

**Comment by andrevmatos** [comment]
Currently, Refund transfers doesn't work. I never met them on real life, not sure if they're still enabled after work on source routing. It is handled for sent transfers only to fail early if we get a refund, but receiving and mediating works didn't include proper handling of Refund transfers due to the need of refunding back or retrying a different route, which isn't quite supported in the SDK yet.
I need to check on how to at least properly comply with protocol on these.

**Comment by christianbrb** [comment]
@hackaugusto How are refund transfers currently handled in the Raiden Python client?

**Comment by hackaugusto** [comment]
@christianbrb refund transfers are currently disabled, the PFS team wants to completely remove them, we need to fix it or an alternative for the same funcitonality.

**Comment by christianbrb** [comment]
@hackaugusto Thanks for your feedback :)
