### ISSUE TITLE
Error message on deposit field in open channel is wrong

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1493]
## Steps to Reproduce
1. Select a token with no balance
2. Select hub
3. Open channel
4. Enter an amount larger than 0

## Expected Result
- Error message telling me, that I don't have tokens to deposit

## Actual Result
- Message `Please enter an amount larger than zero` is shown
   
   ![grafik](https://user-images.githubusercontent.com/35398162/81574662-682f3580-93a6-11ea-9db6-20f6fd58950f.png)

**Comment by kelsos** [comment]
My initial investigation shows that we don't handle 0 decimals properly. All the scenario player tokens are deployed with `0` decimals. Due to the way the ` || ` operator works in JavaScript both `undefined` and `0` are falsy so the code assumes `18` decimals which is wrong. 

I am looking into all the components and creating a fix for specifically handle the `0` decimal case.
