### ISSUE TITLE
I do not want to pay the PFS if it doesn't find a route

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1518]
## User Story

Currently in the Light Client the user flow of a token transfer to a target, you don't have a direct channel with, is as following:

1. Enter target and amount
2. Click continue
3. Select a PFS (optionally mint and deposit SVT to UDC if you haven't yet)
4. Pay the PFS to get a route
5. Receive a route

If the PFS can't find a route, it responds in #5 with error code `2201` (no route between nodes)

From a user perspective this feels odd, because ideally you:
* only want to pay if there is an actual route
* get informed early if there isn't one, so you don't have to pay

CC @christianbrb @karlb @GataKamsky

**Comment by christianbrb** [comment]
@karlb Is there already an issue within the PFS repo which is describing the endpoint changes for this issue?

**Comment by karlb** [comment]
Requiring payments even if there is no route is reasonable because
* the PFS has to do work to find out if there are any routes (not necessarily less work than if a route is found).
* the payment is already sent with the request. Making it depend on the result will make two requests necessary, slowing down the payment and increasing complexity.

I'm open to discuss this, but so far I'm not convinced that a change would be an improvement, overall.

**Comment by karlb** [comment]
> @karlb Is there already an issue within the PFS repo which is describing the endpoint changes for this issue?

As the current behavior is intended, there is currently no such issue. Feel free to open one, if you want to bring the discussion into the PFS repository.

**Comment by taleldayekh** [comment]
Closing, changes needs to be made in the pfs not Light Client.
