### ISSUE TITLE
2nd opened channel with partner not displayed

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1540]
## Steps to Reproduce
1. Mint ETHCC3 tokens and open/deposit channel with hub
2. Mint TTT tokens and open/deposit channel with hub
3. On transfer screen, click channels

## Expected Result
- I see two channels, one with TTT and one with ETHCC3 tokens

## Actual Result

<img width="653" alt="Screenshot 2020-05-15 at 09 31 35" src="https://user-images.githubusercontent.com/3169205/82023659-e6355a00-968e-11ea-9d9b-52b70fd6b469.png">

When I go to my connected tokens, I can see that I'm connected to both of them though:

<img width="649" alt="Screenshot 2020-05-15 at 09 32 01" src="https://user-images.githubusercontent.com/3169205/82023761-09f8a000-968f-11ea-8a36-559526d78bdb.png">

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by kelsos** [comment]
I also got really confused by this. But we are actually are showing the channels for the selected token.
Since the second channel is in the other token it only shows after we select the other token. So the two channels with the same partner will never show in the same channel list. 

![image](https://user-images.githubusercontent.com/2269732/82804450-9cb0f000-9e82-11ea-88cc-b1f45209f039.png)

Since we both become confused about that, we should improve on it. 
There are two paths we can follow:
- Show some kind of information/header that clarifies that these are only the channels for a specific token
- Show all the channels in the list, regardless of the token, and also add the token information.

@nephix @andrevmatos @taleldayekh @christianbrb any input on that? I am ok with either approach but any more ideas would be nice. 

What would your expectations be when entering the `Channels` page? To see only the channels for the selected token, or see all the channels available?

**Comment by christianbrb** [comment]
@kelsos I have created https://github.com/raiden-network/light-client/issues/1460 to improve the transfer screen and especially the top of it. The token / channel / deposit buttons have been a quick fix and need an improvement

**Comment by kelsos** [comment]
We still need to provide some kind of access to the channels screen but we need to rethink on how we can properly do it so that we avoid any confusion.

**Comment by andrevmatos** [comment]
I'm pro having all channels on it, including token information, and then having filters in place for token, partner, and maybe even removing the states sections and instead having those on filters as well.

**Comment by nephix** [comment]
> The token / channel / deposit buttons have been a quick fix and need an improvement

I think since the user is expected to not tinker around most of the time with channels, it might make sense to move it to the account screen and display all open channels in the list

**Comment by kelsos** [comment]
As we discussed in the daily we the team (@taleldayekh @andrevmatos @weilbith) we will go for the simplest solution which is adding a label on top clarifying that these are the channels for a specific token. 

We can move the discussion for further improvement to a new issue since the scope of the discussion is bigger and it might take some time.
