### ISSUE TITLE
Matrix error when connecting to mainnet

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1547]
Not sure if 
* misconfiguration of testenv001, or
* SDK bug or feature request

## Steps to Reproduce
1. Based on #1546
2. Connect to mainnet

## Expected Result
- Can establish a matrix connection

## Actual Result

<img width="794" alt="Screenshot 2020-05-19 at 10 48 50" src="https://user-images.githubusercontent.com/3169205/82313809-2bc49080-99c9-11ea-832e-a33bf3cf1d1a.png">

Maybe we filter/don't fetch this room somehow?

**Comment by christianbrb** [comment]
It needs to use a different environment. Check with @Dominik1999 😊

**Comment by andrevmatos** [comment]
I think this is caused by the global rooms not existing by those names on the testenv transport matrix server. Either or both of:
- mainnet needs to be special cased on the room naming at SDK, as `Network.name` is `homestead`, but the room name needs to be like `raiden_mainnet_discovery` (or is it `raiden_main_discovery`?)
- Need to ensure the rooms are created on testenv Matrix servers
