### ISSUE TITLE
deposit to UDC failing on goerli

### ISSUE THREAD

**Issue by BOR4** [raiden-network/light-client#1637]
## Steps to Reproduce
1. goerli
2. mint and deposit
[raiden_2020-06-05T12 04 21.779Z.log](https://github.com/raiden-network/light-client/files/4735964/raiden_2020-06-05T12.04.21.779Z.log)

**Comment by andrevmatos** [comment]
Ok, I managed to reproduce this here as well. This is caused by services already taking part of your deposit as fees (i.e. PFS, MS), and your new deposit added to UDC's current `balance` not being greater than the total_amount. The bug is caused by we having wrongly having used the balance to calculate the final deposit value (balance + new deposit), while the UDC contract requires the amount to be calculated based on the total_deposit. Fix is on the way.
