### ISSUE TITLE
The transfer screen should show an error to the user if it occurs in the process

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#1651]
## Steps to Reproduce
1. make a mediated transfer
2. Press continue on the transfer screen here 
![transfer_screen](https://user-images.githubusercontent.com/15123108/84140602-80f73d80-aa6f-11ea-89e2-7acc6813a102.png)

## Expected Result
- Screen should show an error which happens on user action and take him out

## Actual Result
- The spinner keeps spinning without showing any error to the user.
![light_client_pfs_not_available](https://user-images.githubusercontent.com/15123108/84140163-cbc48580-aa6e-11ea-8c2c-2e9222f7cbd0.png)
![light_client_console_error_pfs](https://user-images.githubusercontent.com/15123108/84140243-edbe0800-aa6e-11ea-87a8-f37a306a37e3.png)

## Additional Infos (Optional) 
```
- Browser & version
Chrome Version 83.0.4103.97 (Official Build) (64-bit)
- Browser console errors
Screenshots are given above
`type: "path/find/failure", payload: RaidenError: Pathfinding Service is disabled and no direct route is available.`
- Device / OS
Linux mint
```
[raiden_2020-06-09T11_10_08.828Z.log](https://github.com/raiden-network/light-client/files/4751786/raiden_2020-06-09T11_10_08.828Z.log)

**Comment by andrevmatos** [comment]
This is not an error. That PFS "failure" action/log is actually just the response to the direct route check, which happens before the actual PFS request. Your issue is actually that the PFS was disabled from `VUE_APP_PFS` env var missing from my guide and actually being passed as `undefined` and that disabled the PFS fetching, which made the transfer gets stuck waiting for a PFS to show up.
My PR will fix that by also supporting undefined as pfs auto mode. In the meantime, you can just `export VUE_APP_PFS=""` on the terminal before serving the dApp, and this will enable PFS again, as expected.
