### ISSUE TITLE
Create a notification area

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#168]
## Description
As Chris I would like to have all notifications collected in one area.

There should be a notification area where the user can see a notification about the results of actions even if they did end up navigating out of the specific screen.

## Acceptance criteria
- A drawer-style notification panel where notifications get collected based on type of notification.

## Tasks
Look at the notification panel in the WebUI for consistent design

**Comment by christianbrb** [comment]
Proposal from @taleldayekh (see https://github.com/raiden-network/light-client/issues/426#issuecomment-553913346)

![grafik](https://user-images.githubusercontent.com/35398162/69031431-675ead80-09da-11ea-88ff-81954ed7ac44.png)

**Comment by christianbrb** [comment]
It would include pending or executed transfers after #426 has been implemented. Needs slicing anyway.

**Comment by christianbrb** [comment]
@taleldayekh What do think about incorporating this into the "transfer" history.
You would see there the following actions as well:
- Open Channel
- Deposit
- Transfers (as it is right now)
- Withdraw (if implemented)
- Close
- Settled

**Comment by taleldayekh** [comment]
@christianbrb I'm not super convinced that those actions make sense in the transfer history. I believe it is best to keep it as simple as possible, meaning that the transaction history only has the purpose of displaying whether a transfer was sent or received.

**Comment by kelsos** [comment]
I would agree with @taleldayekh on this. For me, it doesn't make sense to add anything other than transfers in the transfer history. We still need notifications, but it would make more sense if they are a completely new area of the application.

**Comment by kelsos** [comment]
Since the identicon now shows the account we can move to a similar approach as the WebUI, and add a notification bell icon to access the notification area. 

You can show a badge for any unread notifications too. 

On a side note, I think that while we all know the purpose of the badge on the identicon if I was a new user I would probably find it unclear on what it represents.

**Comment by taleldayekh** [comment]
I'm pulling this into the iteration (in its most basic form) since it is a prerequisite for many of the things we want to add.

**Comment by taleldayekh** [comment]
After some thinking about this, I arrived at the following conclusions. Let me know what you think.

I don't think it is a good idea to introduce another "overlay/menu/drawer" just to hold notifications. I especially don't think a drawer-style notification panel would fit with our current design. Where would it appear from? It would look strange since the dApp is centered in the browser window.

Instead, I would prefer keeping the notification badge on top of the identicon and add another item on the account screen called `Notification` where a user can access all notifications if they desire.

We could also add a banner whenever a notification happens that gives the user a preview of the notification as used in the WebUI.
![mockup_notifications](https://user-images.githubusercontent.com/43838780/83261165-38ac6580-a1bb-11ea-8ef2-b217cc251407.jpg)

**Comment by taleldayekh** [comment]
We will go with a second icon next to the identicon for the notification area. Consensus was that a user want to access the notifications with one click only.
