### ISSUE TITLE
What happens to imbalance fees with a Light Client not being capable to mediate transfers?

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1700]
## Description
Currently, mediating transfers is disabled for the Light Client. What is the impact of imbalance fees if a Python client assumes, that the Light Client is a mediating node.

@Dominik1999 Could you explain your remark in detail? Thanks :)

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
As I explained on https://github.com/raiden-network/light-client/issues/1699#issuecomment-644318088, the transfer won't succeed. Meanwhile it's pending/locked though, the imbalance fees for any already walked stretch of the mediation path will stay increased due to the capacity reduction by this transfer. This is a non-issue on the non-mediating LC hop, since it doesn't mediate, and on any previous hop, it'll get reset when the 'offending' `LockedTransfer` is expired, so protocol is consistent on this case as well. Again, any hop can/should be able to prevent this by inspecting the `noMediate` capability, but it's just an optimization, the protocol works fine if any node does or doesn't do that.

**Comment by christianbrb** [comment]
@andrevmatos Cool, thanks :)

@Dominik1999 Does this sounds reasonable for you?

**Comment by Dominik1999** [comment]
That sounds reasonable to me

**Comment by christianbrb** [comment]
Thanks for the feedback :) Closing :)
