### ISSUE TITLE
I want all transfers to be monitored

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1705]
## User Story
As Chris I want all transfers to be monitored so that I feel safe when receiving transfers

After the decision to close #1654 we need to monitor all receiving transfers.

## Solution
From https://github.com/raiden-network/light-client/issues/1513
> Setting it to INF~=MaxUint256 would enable receiving and send monitoring request for any received transfer (user's call)

We should set this `ratetoSVT`automatically when he is connecting to the a new token.

CC @andrevmatos

**Comment by andrevmatos** [comment]
Ok, this is feasible. Just a question though: could/should we do that only for tokens which have channels the user interacted with (opened by, deposited by or with transfers from the user), to possibly avoid this quicking in for random TokenNetworks?

**Comment by christianbrb** [comment]
Yes, we should just do this for TokenNetworks where we have deposited.

**Comment by christianbrb** [comment]
@andrevmatos to describe the design and @weilbith  to implement

**Comment by andrevmatos** [comment]
Ok, this maybe simpler than supposed.
There's a couple of things to have in mind:
- receiving can be disabled or enabled in a couple of way
  - by `config`, it can be strictly set to enabled or disabled, which has precedence
  - if not set, it's in a kind of 'auto' mode, where it gets enabled (globaly) based on a couple of conditions, most relevant here are: `monitoringReward` must be set and positive (already by default), `udcBalance` must be higher than `monitoringReward` and `rateToSvt` must not be empty
- if it's enabled, when the partner's balance of a channel changes, `monitorRequestEpic` will validate if we should or not compose and send a `MonitoringRequest` for this channel, which also gets filtered by a couple of conditions:
  - most relevant here is: if the specified token is present on the `rateToSvt` mapping, it uses this exchange rate to convert the channel's current _amount to lose_ in case of not getting updated to the SVT basis, and compare that this value is higher than what we'd pay for `monitoringReward`, and if greater, it signs and sends a MonitoringRequest for this channel
  - if there's no `rateToSvt` for this token, it defaults to `Zero`, which skips MS request for any value, effectivelly disabling MS (but allowing receiving the transfer) for this channel

So, I'd like to keep this `rateToSvt` mechanism if present, so if the user or developer reads docs and decide to use it to implement this 'filtering' for sending a MS, they should still be able to do so, but this issue is about not making it required, and instead have the fallback of always sending a MS request, as soon as the user has ever made any deposit to the channel (meaning it's a channel of interest). With it, one will also always be able to explicitly disable MS for a token by setting its rateToSvt explicitly to Zero, which ensures it'll me skipped for any channel amounts.

This can be done by making the following changes:
- [ ] `rateToSvt` being empty should not be a condition anymore for enabling receiving (disabling `noReceive` capability)
- [ ] if `rateToSvt` is not set for channel's token, it must default to `MaxUint256`, which is a constant which ensures MS is sent for any (positive) partner's value
- [ ] If `ownDeposit` for channel is Zero, skip as well (we already to a check that `partnerUnlocked` must be greater than Zero, so just at it there as well)
