### ISSUE TITLE
Number of messages to sign on Open Channel

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1779]
## Steps to Reproduce
1. Click on "Open Channel"

## Expected Result
- I get the message, that I have to sign 4 messages (or 5 -> I am not 100% sure)

## Actual Result
- I get the message, that I have to sign 2 messages 

![grafik](https://user-images.githubusercontent.com/35398162/85509416-46a4a900-b5f6-11ea-9b4a-753194a30f10.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by kelsos** [comment]
Opening a channel is 3 on-chain transactions normally, one to open the channel and two to approve and deposit the tokens to the said channel. 

This dialog's text refers to the approval and deposit transactions and was initially introduced because we didn't have a way to separate the approval step from the deposit step. So initially we intended to have a 3 step/message dialog but since we could not differentiate between the last two steps, this dialog message was introduced.

**Comment by christianbrb** [comment]
Ah ok, that's confusing. Closing the issue.
