### ISSUE TITLE
Open Channel Modal is not closing

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1780]
## Steps to Reproduce
1. Navigate to Select Hub
2. Enter hub.raiden.eth
3. Click on Select Hub
4. Enter an amount
5. Click on Open Channel
6. Sign all the messages (Last one: Set Total Deposit - Confirmed)

## Expected Result
- I am getting redirected to the transfer screen

## Actual Result
- The modal screen is open and the spinner spinning

Logs: 
[Todays_logs.txt](https://github.com/raiden-network/light-client/files/4823760/Todays_logs.txt)

## Additional Infos (Optional) 
```
- Firefox
```

**Comment by andrevmatos** [comment]
I can't explain nor reproduce this issue. On the logs, I can see the channel request action with a deposit, the channel open success and confirmed success actions and monitor, but no logs about approve/deposit nor deposit actions going through. I can't see how this can be possible with the current code. The only explanation would be that some of the deposit tx prompts got hidden by Metamask and stood stuck without neither reply nor rejection, otherwise we would see at least failure.
I just tested the workflow, and it's working fine here.

**Comment by christianbrb** [comment]
I have signed all transactions in MetaMask

Time is 2 hours off (I think we are logging in UTC, right?)

![grafik](https://user-images.githubusercontent.com/35398162/85567036-d1a29500-b630-11ea-98ac-078f73964156.png)

**Comment by andrevmatos** [comment]
So, the `channelOpenEpic` did act as expected, but the events were not picked up by `channelMonitoredEpic`. I'm trying to make it more reliable.
