### ISSUE TITLE
Raiden stops suddenly

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1805]
## Steps to Reproduce
1. Use the dApp
2. Keep it unattended

## Expected Result
- dApp is running

## Actual Result
- dApp stops with `{"type":"raiden/shutdown","payload":{"reason":"raidenStopped"}}`

[2020-06-25T07_log.txt](https://github.com/raiden-network/light-client/files/4830349/2020-06-25T07_log.txt)

## Additional Infos (Optional)

**Comment by kelsos** [comment]
That is interesting, for this to happen it means that the shutdown was called by the App. The only change of this happening is hwne the `App.vue` component gets destroyed.

**Comment by weilbith** [comment]
@christianbrb any approximately time value for testing? Did you left if open over night or...?

**Comment by weilbith** [comment]
Okay, let's be a bit more precise. There are three places where Raiden gets stopped. First is the `disconnect()` function of the Raidne service class. This function is exclusively used by the tests for now. The next occurrence is when the user does a backup of the state. Since that's not what Christian did, also not the target. The last place where we stop Raiden is when the page gets unloaded. That is was Kelsos was referring to. So when the browser is about to unload the page, we have a hook that stops Raiden before that happens.

As I knew so far the unloading happens when you close the tab, reload or switch to a new page int the same tab. Nothing that happens automatically after a while. So which web-browser are you using @christianbrb ? Maybe they have a listing when they call to unload. For example was there [an announcement](https://www.ghacks.net/2019/03/01/firefox-67-automatically-unload-unused-tabs-to-improve-memory/) that Firefox will automatically unload unused tabs to save memory. Not sure if this is already live.

My suggestion would be that we prevent the unloading. So like other web-applications with unsafed data I would call `preventDefault()` on this event. So this usually opens a pop-up if the user want to continue or stay on the page. I would assume that even auto-unload will respect this to protects users from eventually lost data.

**Comment by christianbrb** [comment]
I am using Firefox and it took 1-hour maximum.

**Comment by weilbith** [comment]
Okay so how did the final result looked like? A blank white page or..?

**Comment by christianbrb** [comment]
The final result: The connect screen has been shown.

**Comment by weilbith** [comment]
@kelsos what is your opinion on this suggestion?

> My suggestion would be that we prevent the unloading. So like other web-applications with unsafed data I would call preventDefault() on this event. So this usually opens a pop-up if the user want to continue or stay on the page. I would assume that even auto-unload will respect this to protects users from eventually lost data

**Comment by kelsos** [comment]
@weilbith I am not really sure. What happened to @christianbrb was probably due to the `destroy` lifecycle hook of `App.vue` being called, not an event. So I am not sure what we would need to prevent here. I would have to check the documentation again, in regards to the Vue component lifecycle.

**Comment by weilbith** [comment]
Hmm. But shouldn't `vm.$destroy()` on the main component only be called on unloading the page? So I actually think we stop Raiden twice...

**Comment by kelsos** [comment]
I am not sure where the second place is. Could you point to that?

**Comment by weilbith** [comment]
Your `App.destroy()` is [here](https://github.com/raiden-network/light-client/blob/58cae0cc44c6fb3583f6c8b6864231f36a18cef4/raiden-dapp/src/App.vue#L53). The window event hook within `RaidenService.connect()` [here](https://github.com/raiden-network/light-client/blob/58cae0cc44c6fb3583f6c8b6864231f36a18cef4/raiden-dapp/src/services/raiden-service.ts#L223).

**Comment by weilbith** [comment]
Unfortunately I can't emit the unload event manually. But using some log messages and a persistent log I see that only the window event hook gets called. The `App.destroy()` does not log that is got called....

**Comment by kelsos** [comment]
ok so basically it is probably what you mentioned before, firefox unloading the tabs after a while

**Comment by weilbith** [comment]
According to my link this has been introduced on Firefox `67`. So I'm definitely having it.  And I would assume Christian as well. So I'll go for a long duration test now. Trying to reproduce the issue and then check if preventing the event helps.

**Comment by weilbith** [comment]
Okay yesterday it did not happen for me anymore. But I kept in running the night closed an opened it for work this morning. Visiting the tab again no caused a reload for me. Again no destroying of the `App` component.
So I'll try to do it again with the event preventing implementation.
