### ISSUE TITLE
Introduce route or urls to notification payload and implement mechanism to follow up routes on user action

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1901]
Also, no need to hard push it this PR if too complex, but `NotificationPayload` could have an optional `route` or `url` which, when set, could make this whole element a link to the respective route. e.g. Receive Disabled notification above could direct to the UDC screen.

_Originally posted by @andrevmatos in https://github.com/raiden-network/light-client/pull/1842/files/55ac766fa300958a3642aa66b4b62bef7db6028c_

**Comment by christianbrb** [comment]
A nice to have. Closing

**Comment by andrevmatos** [comment]
Wait.. if you close "nice to have", how are we expected to remember them in the future? I thought the point about these issues were to keep track of ideas to not lose them, and this one continues to valid. Unless we decide this is not going to be done at all.

**Comment by christianbrb** [comment]
If they are important we are going to remember it :) If not, they are not important.

Having a high inventory on issues is a burden. It costs hours and hours to maintain them, they get outdated, fixed by other issues/PRS, loose context. We have to read them over and over again and we even track them in our brain.
