### ISSUE TITLE
URL Parameters and path do not work any more

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1931]
## Steps to Reproduce
1. Navigate to https://hub.raiden.network/
2. Click on "Open Channel with Hub"

## Expected Result
- A prefilled connect screen is shown

## Actual Result
- A white screen is shown

## Additional Infos (Optional) 
- This also applies to other links for example when I am reloading a screen.

**Comment by christianbrb** [comment]
It also doesn't work if I reload a page
eg. https://lightclient.raiden.network/staging/connect

**Comment by taleldayekh** [comment]
@andrevmatos I believe changes need to be made in the Raiden hub code? Because "Open channel with hub" generates a link without the hash.

**Comment by taleldayekh** [comment]
I made the changes here: https://github.com/raiden-network/raiden-hub/pull/26

**Comment by andrevmatos** [comment]
We'll also need a new release, since lightclient.raiden.network is only deployed on tag

**Comment by christianbrb** [comment]
There is one issue with the current implementation.

### Steps
1. Navigate to hub.raiden.network
2. Click on "Open channel with hub"
3. Change the URL to https://lightclient.raiden.network/#/connect/0xE2b702eD684bEb02850ac604278f078A4ce8b6E6/0x1F916ab5cf1B30B22f24Ebf435f53Ee665344Acf?deposit=0.01

### Expected Result
- I can click on connect and hub address is shown

### Current Result
- I cannot click on connect and hub address is not shown
   
![grafik](https://user-images.githubusercontent.com/35398162/89421455-5b677700-d734-11ea-8ac4-c8d5c9a1bc8b.png)

**Comment by taleldayekh** [comment]
On closer inspection, I suspect that it might be related to this script in our `index.html`. As I understand it, this was implemented for allowing history mode? If so, does this mean that `hash` mode is the default on GitHub pages? @andrevmatos @weilbith do you have an insight in this and are my assumptions correct?

```
    <script type="text/javascript">
      // Single Page Apps for GitHub Pages
      // https://github.com/rafrex/spa-github-pages
      // Copyright (c) 2016 Rafael Pedicini, licensed under the MIT License
      // ----------------------------------------------------------------------
      // This script checks to see if a redirect is present in the query string
      // and converts it back into the correct url and adds it to the
      // browser's history using window.history.replaceState(...),
      // which won't cause the browser to attempt to load the new url.
      // When the single page app is loaded further down in this file,
      // the correct url will be waiting in the browser's history for
      // the single page app to route accordingly.
      (function (l) {
        if (l.search) {
          var q = {};
          l.search.slice(1).split('&').forEach(function (v) {
            var a = v.split('=');
            q[a[0]] = a.slice(1).join('=').replace(/~and~/g, '&');
          });
          if (q.p !== undefined) {
            window.history.replaceState(null, null,
              l.pathname.slice(0, -1) + (q.p || '') +
              (q.q ? ('?' + q.q) : '') +
              l.hash
            );
          }
        }
      }(window.location))
    </script>
```

**Comment by taleldayekh** [comment]
Additional information:

```
#### Notes on client-side routing
GitHub Pages doesn’t support routers that use the HTML5 `pushState` history API under the hood (for example, React Router using `browserHistory`). This is because when there is a fresh page load for a url like `http://user.github.io/todomvc/todos/42`, where `/todos/42` is a frontend route, the GitHub Pages server returns 404 because it knows nothing of `/todos/42`. If you want to add a router to a project hosted on GitHub Pages, here are a couple of solutions:
* You could switch from using HTML5 history API to routing with hashes. If you use React Router, you can switch to `hashHistory` for this effect, but the URL will be longer and more verbose (for example, `http://user.github.io/todomvc/#/todos/42?_k=yknaj`). [Read more](https://reacttraining.com/react-router/web/api/Router) about different history implementations in React Router.
* Alternatively, you can use a trick to teach GitHub Pages to handle 404 by redirecting to your `index.html` page with a special redirect parameter. You would need to add a `404.html` file with the redirection code to the `build` folder before deploying your project, and you’ll need to add code handling the redirect parameter to `index.html`. You can find a detailed explanation of this technique [in this guide](https://github.com/rafrex/spa-github-pages).
```

**Comment by taleldayekh** [comment]
Some additional information found in: https://itnext.io/so-you-want-to-host-your-single-age-react-app-on-github-pages-a826ab01e48

#### Notes on client-side routing
GitHub Pages doesn’t support routers that use the HTML5 `pushState` history API under the hood (for example, React Router using `browserHistory`). This is because when there is a fresh page load for a url like `http://user.github.io/todomvc/todos/42`, where `/todos/42` is a frontend route, the GitHub Pages server returns 404 because it knows nothing of `/todos/42`. If you want to add a router to a project hosted on GitHub Pages, here are a couple of solutions:
* You could switch from using HTML5 history API to routing with hashes. If you use React Router, you can switch to `hashHistory` for this effect, but the URL will be longer and more verbose (for example, `http://user.github.io/todomvc/#/todos/42?_k=yknaj`). [Read more](https://reacttraining.com/react-router/web/api/Router) about different history implementations in React Router.
* Alternatively, you can use a trick to teach GitHub Pages to handle 404 by redirecting to your `index.html` page with a special redirect parameter. You would need to add a `404.html` file with the redirection code to the `build` folder before deploying your project, and you’ll need to add code handling the redirect parameter to `index.html`. You can find a detailed explanation of this technique [in this guide](https://github.com/rafrex/spa-github-pages).

**Comment by taleldayekh** [comment]
Looked into this with @weilbith and the issue is related to an outdated contract version. The hub needs to be updated to the new versions for this issue to be solved.

**Comment by weilbith** [comment]
I'm taking over from here to do the deployment. I'll integrate Talel into the process.

**Comment by weilbith** [comment]
Just to give an update here. The new resource image was built and successfully tested. The link works fine now.
The deployment is on halt for an still open PR at the resource repository including a bunch of fixes. Furthermore is the domain routing not clarified yet, since this has to change and wasn't forgotten by Niels. I'm in a conversation with Ulo for this.

**Comment by weilbith** [comment]
Deployed and available.
