### ISSUE TITLE
Event filtering performance problems

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#1955]
Event filtering done by the Ethereum client is very inefficient, event filtering is done by a linear search with an exclusive lock acquired. Because of the lock, both geth and parity/openethereum clients, will satisfy only *one* getLogs request at a time. Because of the linear search these requests can be considerably slow.

I tried to understand how the event filtering is being performed in the light client, and from what I gathered there are multiple observables for event filtering created:

- There is one event stream for the PFS registry, MS monitor, and the secret registry
- One for new blocks
- One to fetch old events of channels with a limited life time, and another one to fetch new logs for a given channel

Additionally, the algorithm doesn't seem to adapt the querying range, meaning that on startup a long range can be used, which will be queried `confirmations * 2` times until the range is reduced. This will be a performance bottleneck and will most likely lead to scenario failures.

My suggestion is to:

- Only do a single request for all events per client
- Have an adaptive range, with an upper and lower bounds for the number of blocks requested, this range must be decreased if a timeout occurs
- Simplify the existing algorithm and only fetch confirmed events once
   - If I understand correctly the rationale for the current number of retries is because events may be missing from some providers. It would be interesting to see when this happened because the performance cost of fetching the events multiple times is considerable.

**Comment by andrevmatos** [comment]
Thank you very much, Augusto, for taking the time to look into the code.
The event filtering doesn't actually seem to be an issue so far. The Light-Client is able to finish its **initial** sync and be completely ready in around 8s, with the past fetchLogs taking around 4s of them (on my link from Brazil with bb's geth goerli node).
This works by us being very strict on past events we fetch (only logs from channels with us), and only being more permissive on filters for new events, where the bottleneck is on the number of requests done. For this, we reduced dramatically the number of `getLogs` **per block**. We monitor all channels events on each TokenNetwork with a single call per block, and then the one for each of the other 3 you mentioned.
About the adaptive query range, it actually is adaptable for confirmed new events. Any confirmed event is queryed at most once, but unconfirmed events (i.e. on the last 'confirmations' blocks) are fetched 'confirmations' times, but this is intended. This is done by that `afterLogBlocks` `splice` on the `fromEthersEvent` function.
This algorithm proved to be the only one reliable so far on Infura, where we often get empty responses due to their loadbalancing of servers.
Fortunately, as I said, the confirmed events do cap the long initial ranges, and ensure we don't lose events by giving them up to `confirmations * 2` chances of getting fetched, but on average at most `confirmations` being needed. 
It'd be interesting to possibly do a call to discuss the algorithm, as it's one of the most critical parts of the system.
That said, we have some points for optimization. Some filters fetch from deployment block each session, which was done in a time we didn't have an algorithm as reliable as the current one (e.g. the secrets filter). By trusting the current pattern (which is quite new), we can instead rely on the setup of last seen block (done on constructor by `resetEventsBlock`) to query strict ranges, although keeping the _moving ranges_ algorithm for events. I'll make a PR soon to adapt these 'lost' events streams. Thank you very much for the suggestions, they're mostly appreciated.

**Comment by andrevmatos** [comment]
Another optimization we look forward to test in the future is to use filters with multiple `address` fields (i.e. fetching different contracts events on a single `getLogs` call per block, even on different contract types!). Since we can do client-side filtering, and the number of events on new blocks isn't expected to be too big, this actually would be the ultimate optimization, and allow for very lightweight usage of Infura or ETH node, even while keeping the _moving window_ algorithm for reliability.

**Comment by hackaugusto** [comment]
> This works by us being very strict on past events we fetch (only logs from channels with us), and only being more permissive on filters for new events, where the bottleneck is on the number of requests done.

There is a problem here, you're assuming there will be a performance improvement if the log types are limited, this is not true since neither of the mentioned clients has any indexes to accelerate the read based on that, every query performs a linear search were the cost of the operation is proportional to the block range. I have a bit more of documentation written here: https://github.com/raiden-network/raiden/blob/883ec70b7799593c521b40f6295b2abc6696fa63/raiden/blockchain/events.py#L371

> Any confirmed event is queryed at most once, but unconfirmed events (i.e. on the last 'confirmations' blocks) are fetched 'confirmations' times, but this is intended.

There are two problems here:

- On startup the range can be arbitrarily large, and this query will be performed `2*confirmation_block` times. Note: I read the logic a few days ago and I don't recall the details precisely, but I believe the range is only reduced after an array length reaches the aforementioned number of entries, which is potentially lots of slow queries.
- Were are talking about two different ways of adapting the range. Since the cost of the operation is proportional to the block range, and there will be only one such request served at a time, if an operation fails the range has to be reduce with the assumption that are too many blocks or too many concurrent requests. If the range is not reduced initialization will fail. 

> The event filtering doesn't actually seem to be an issue so far. The Light-Client is able to finish its initial sync and be completely ready in around 8s, with the past fetchLogs taking around 4s of them (on my link from Brazil with bb's geth goerli node).

This is only a problem for geth or openethereum/parity, under mainnet, with many concurrent users, and a old deployment of the smart contracts. But unless the clients implement indexing for event filtering it will still be a problem, there are issues commented on the code I linked above with more details.

**Comment by andrevmatos** [comment]
> There is a problem here, you're assuming there will be a performance improvement if the log types are limited, this is not true since neither of the mentioned clients has any indexes to accelerate the read based on that, every query performs a linear search were the cost of the operation is proportional to the block range. I have a bit more of documentation written here:

No, my assumption is not that there'll be an index to reduce the complexity of the query, but instead that there'll be as little events to return on these requests as possible. In our experiments, the number of blocks in the range had a smaller impact then the size of the response payload, and with our filters, we make sure we don't need to fetch events we don't care for (at least not on initial sync).

> * On startup the range can be arbitrarily large, and this query will be performed `2*confirmation_block` times. Note: I read the logic a few days ago and I don't recall the details precisely, but I believe the range is only reduced after an array length reaches the aforementioned number of entries, which is potentially lots of slow queries.

This ensure this isn't the case: if there's any confirmed event matching the filter coming on even the first request, we can be sure that at least up to the that event's blockNumber, the node was synced and returned any event, so we can adapt the range.
https://github.com/raiden-network/light-client/blob/5b3bfb9b26f9f090f787d321b4b1214dfaa2dde7/raiden-ts/src/utils/ethers.ts#L76-L89

> * Were are talking about two different ways of adapting the range. Since the cost of the operation is proportional to the block range, and there will be only one such request served at a time, if an operation fails the range has to be reduce with the assumption that are too many blocks or too many concurrent requests. If the range is not reduced initialization will fail.

There's a `exhaustMap` there which helps us make sure we don't make two concurrent calls to the same contract, and as I said, if there're any confirmed event on the range even on first call, it'll reduce the range right away. This also doesn't timeout, and upon any network request, is retried on next `block`. Thank you for the headsup though, we'll test on the Mainnet and check how long we take to fully initialize there and adapt the algorithm if needed.

**Comment by hackaugusto** [comment]
> No, my assumption is not that there'll be an index to reduce the complexity of the query, but instead that there'll be as little events to return on these requests as possible

The point I'm trying to make is that less entries in the response *does not necessarily* reduce the query runtime, *an index is necessary* for the speed up to happen.

For example, assuming this schema:

```sql
-- This is just an example, AFAIK the clients use key-value stores and not relational
-- databases, I'm just using this to make it a bit clearer the runtime costs
-- I'm talking about

CREATE TABLE eth_blocks
( 
    canonical_chain bool,
    block_number integer NOT NULL,
    block_hash bytea NOT NULL,
    bloom NOT NULL,

    -- Note this the only index, so reading blocks from the canonical chain in
    -- order is the only operation which is fast, everything else is a linear scan.
    PRIMARY KEY (canonical_chain, block_number, block_hash)
);

CREATE TABLE eth_logs 
( 
    id integer PRIMARY KEY,
    block_hash bytea NOT NULL REFERENCES eth_blocks (block_hash) ON DELETE CASCADE,
    topic bytea, -- simplified for the sake of the example
    smart_contract_address bytea,
    log bytea NOT NULL
);

-- Note the only index here is to find logs of a block, everything else requires scanning
CREATE INDEX idx_log_to_block ON eth_logs (block_hash);
```

Searching for particular logs would be done by something roughly like:

```sql
-- Again, this is hypothetical, a rough translation of the code equivalent SQL

SELECT eth_logs.log FROM eth_logs, eth_blocks WHERE
  eth_logs.block_hash = eth_blocks.block_hash AND
  eth_blocks.canonical_chain = true AND
  eth_logs.smart_contract_address IN (<contract_addresses>) AND
  eth_logs.topic IN (<topics>) AND
  eth_blocks.block_number BETWEEN <start> AND <end> AND
  eth_blocks.bloom & <topics> = <topics>;
```

Note that the DDL does not have any indexes for `eth_logs.topic` nor `eth_logs.smart_contract_address`, these additional filters will reduce response size, but *they won't* speed up query runtime. The `eth_blocks` table will have to be *scanned* for the range of the block numbers, and the `eth_logs` table will be read for any matches (In a relational database this order could be reversed, but AFAIK this is the order used by the clients). In theory the bloom filter would improve performance by reducing the number of matches in the `eth_blocks` table, resulting in less lookup in the `eth_logs` table, however, bloom filters are probabilistic by design, and the false-positives increases in proportion to the number of elements being indexed.

To conclude, saying that `less elements == faster queries` **has** an assumption that there is a index backing up the query, which is not necessarily true.

**Comment by andrevmatos** [comment]
In a call with @hackaugusto , we clarified the algorithm, how it's supposed to optimize the common case, and that we'll run reallife tests, possibly including old RedEyes contracts, to check the true efficiency of the current algorithm.

**Comment by hackaugusto** [comment]
Here are some refs from the Python repo:

- Performance measurements: https://github.com/raiden-network/raiden/pull/6066
- Rationale for 10 second timeout and adaptive range: https://github.com/raiden-network/raiden/issues/6081#issuecomment-615280442
- Rough estimation of the number of nodes that can run with a single geth instance: https://github.com/raiden-network/raiden/issues/6106
- Early occurrence of the problem with red eyes: https://github.com/raiden-network/raiden/pull/3617

**Comment by christianbrb** [comment]
I assume this is fixed as the Raiden client is going to use the Light Client approach.

@andrevmatos Please reopen, if this is not the case.
