### ISSUE TITLE
Change matrix servers while running

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#1973]
Every now and then we run into a few issues with one of the servers in the federation, these errors are usually transient but last long enough to force a node offline if connection errors are propagated. I have not understood fully how the light client handles matrix errors, but it seems that after startup the server with the lowest latency at that time is chosen and can not be changed. In order to increase reliability of the client I'd suggest implementing retries under some errors 5xx, 4xx for endpoints that are known to exist (e.g. posting a message to a room), and timeouts.

**Comment by andrevmatos** [comment]
This would be a good enhancement I've been keeping in the back of my mind for some time already. Thanks for bringing this up.
Our transport is already quite reliable at startup, since it can identify a chosen server misbehaving and try the next whenever possible, but definitely it'd be great to also detect failures at runtime and redo init & auth steps, and be able to recover in a different server. `switchMap` and friends can help the respective epics here.

**Comment by taleldayekh** [comment]
Closing, since we are probably moving away from Matrix and even if we stick with Matrix this is not big enough of an issue.
