### ISSUE TITLE
Conversion issue for UDC deposit and RDN acquisition on mainnet 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2047]
Test UDC deposit and RDN acquisition on mainnet

**Comment by agatsoh** [comment]
On the UDC screen we have this line which shows the UDC balance 

**Your current UDC balance is: 10.0 RDN**
Just below that we must specify that the `RDN` balance for our account is zero
because 
When I  click on deposit we get this dialog and it shows
`Available RDN to deposit: 0`
The user might get confused that he just saw the RDN balance to be 10 but now here he sees that his RDN balance is 0
But the user does not know that `10 RDN` is the one that he already deposited to the UDC and not the RDN balance of his account

![udc_deposit_dialog](https://user-images.githubusercontent.com/15123108/89636742-b7620500-d8c6-11ea-9c06-f8b32f879dbc.png)

So i went ahead and bought `5 RDN` on uniswap and came back.
clicked deposit and then i got this 

![deposit5rdn](https://user-images.githubusercontent.com/15123108/89636848-e4161c80-d8c6-11ea-8708-2fed13c02245.png)

After clicking on deposit i get this error
![insufficient_balance](https://user-images.githubusercontent.com/15123108/89637592-0492a680-d8c8-11ea-8f96-46f1a5b4bf60.png)

I think its mostly because there is a conversion issue between RDN and REI
