### ISSUE TITLE
Transfers are identified by their secret hash

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2067]
## Description
I found that transfer are identified by their secret hash which is used to lock them. For me that raises the question if that is really save to do, or if there could be several outgoing transfers with the same secret hash that could cause problems. I did not find a problem with it, but it looks fishy to me. 

_Copied from the team repo_

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
Our thinking is that this shouldn't be an issue. If there's a conflict, it's most likely a retry, and we're stricter in not sending or not receiving a transfer with a secrethash collision, so at worst case, it'd prevent us from receiving said transfers. A little bit more thinking can be put here though. @hackaugusto do you see any drawback of the current way we do things, of uniquely identifying transfers by direction and secrethash?

**Comment by hackaugusto** [comment]
I would fix this, the idea is that a payment may be split into multiple transfers, which would use the same secrethash  https://github.com/raiden-network/raiden/issues/3520 , ignoring multiple transfers with the same secrethash can lead to synchronization problems in the future.

**Comment by andrevmatos** [comment]
@hackaugusto What then would be the ideal unique identifier/primary set of values for transfers, in your view?

**Comment by hackaugusto** [comment]
I don't think there is any unique identifier for transfers.

I would group transfer as follows:

- for the initiator `target, payment_id`
- for the target `initiator, payment_id`
- for a mediator just having a list of transfers instead of one transfer per secret hash is enough.

**Comment by andrevmatos** [comment]
@hackaugusto I understand the grouping part for a payment, but for our logic, we really need to know something that represents uniquely a transfer, to have it as key in the state. Would the `secrethash` be a unique identifier **per channel** for a single transfer?

**Comment by hackaugusto** [comment]
> Would the secrethash be a unique identifier per channel for a single transfer?

I wouldn't assume this, there is nothing that guarantees that would be the case.

**Comment by andrevmatos** [comment]
Yes, sure, theré s nothing that guarantees, besides protocol rules and implementation, and we write those. If we say (and implement) that another transfer with same secrethash on the same direction on a given channel should be unique, and a message should be rejected if it conflicts (or be replied with a Processed to confirm as a retry, or whatever), whoever doesn't follow will get theirselves out-of-sync.
AFAIK, this is already the case today with both implementation, since they always generate unique secrethashes which are used for single routes or fail. The LC's current implementation happen to also require it across channels, but since the python implementation unintendedly comply, this can be assumed, right?
This may not (yet) be written, but we could do it eventually, unless you see something explicit which would cripple some other part of the protocol by making this rule definitive.

**Comment by christianbrb** [comment]
Closing -> see https://github.com/raiden-network/light-client/issues/2067#issuecomment-674300319
