### ISSUE TITLE
Missing overflow check for lock.amount

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2078]
Similar to #2058, #2059, and #2063 

https://github.com/raiden-network/light-client/blob/0abfd9ee9d4359b150048f7018dd13fe07175086/raiden-ts/src/transfers/epics/locked.ts#L137

Is not checking for overflow.

**Comment by hackaugusto** [comment]
I'm not going to open more issues about overflows. Ideally casts should not be used since that is error prone

**Comment by andrevmatos** [comment]
Thanks, @hackaugusto . Casts are needed here in places where we **know** the value is in the given range, since they don't have runtime impact, while the validation does, but definitely we should check on the arithmetic operations (like `.add`) to avoid getting overflown there. Thanks for the headsup.
