### ISSUE TITLE
Update the documentation of the SDK regarding the storage persistence changes

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2157]
### Description
Update the documentation of the SDK regarding the storage persistence changes done in #2044

### Acceptance criteria
- Having a conceptual diagram
- Not too detailed - keep it simple

**Comment by palango** [comment]
@andrevmatos Is there any more documentation then in the PR https://github.com/raiden-network/light-client/issues/2044?
@christianbrb Should this go into `SDK-Developmend.md` or some other place?

**Comment by weilbith** [comment]
After some back and forth here is my first version of a structure diagram. It already removes the old migration strategy from `localStorage` as we agreed on. 

---

**ASCII version**: 
(could go as is into a markdown file)

```
                         +--------------------+
                         |       State        |
          .............. |      [Redux]       | <.............
          .              |    (in memory)     |              .
          .              +--------------------+              .
          .                        ^                         .
          .                        .                         .
   async sync back         load data on start        read historic data
          .                        .                         .
          .                        .                         .
          .              +--------------------+              .
          .              |     Database       |              .
          .............> |     [PouchDB]      | ..............
                         |(persistent storage)|
                         +--------------------+
                                   ^
                                   |
          +------------------------+------------------------+
          |                        |                        |
+--------------------+   +--------------------+   +--------------------+
|  LevelDB Adapter   |   | IndexedDB Adapter  |   |   Memory Adapter   |
|     (NodeJS)       |   |   (Web-Browser)    |   |      (Tests)       |
+--------------------+   +--------------------+   +--------------------+
```

---

or

---

**Proper image version:**
(we would need to have maintain the sources, image generation etc.)

![DataStorageGraph](https://user-images.githubusercontent.com/12543647/107205321-09aeea80-69fe-11eb-8043-669fc1d31f10.jpg)

---

**Additional Notes:**

- the database adapter gets chosen based on the environment the SDK is running inside
- the hot state in memory with Redux is limiting its size and therefore does not include historic data of transfers and channels
- the data synchronization from the fast memory to the slower database does not block the protocol logic and gets minimized by state diffs
- the database is used as source to do dump a backups or load such one (can be transferred between clients)
- old database scheme versions get automatically migrated during startup before loading into the Redux state
- clients requests which try to read historic data might be slower due to the database read, while all protocol relevant operations are blazing fast, operating on in-memory data

---

@andrevmatos would be cool if you could have a look here. I'll open the actual PR as soon  as we have decided how to draw the graph.
