### ISSUE TITLE
Strategy on how to improve unit testing in the dApp

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2186]
## Description
Write down a strategy (checklist) on how to improve unit testing (including research) in the dApp and try it in on one component.

## Acceptance criteria
- We spend one day on this task

## Tasks
- [x] Write down summary @weilbith 
- [ ] Create follow up issues @weilbith

**Comment by weilbith** [comment]
Due to my current private situation I would still like to work some days from home. As I highly suggest we should have tackle this issue on one intensive day together in the office. @taleldayekh @palango are you fine to do this later this iteration like next Wednesday or so?

**Comment by weilbith** [comment]
The [Vue Test Utils](https://vue-test-utils.vuejs.org/) are defacto the standard for testing Vue components in "unit" manner. They basically provide everything you need for it.
Else we use Jest as general testing framework for JS/TS. Would be good to know it's basics. Although there is not much special about it and nothing new to learn in comparison to many other frameworks also for other languages.

**Comment by weilbith** [comment]
Notes from our meeting and what we have written down/agreed on. @taleldayekh
@palango please correct me if I misunderstood something, presented wrong or
forgot.

### Goals

- Managing tests should become easy for the daily work of a developer.
- Tests should support the developer, giving him the freedom to change code, while making sure all requirements are still fulfilled.
- Tests of one unit should not fail because another unit has changed.
- Tests should not provide mocks for child-components.
- Everyone looking at the describe block of a unit should be able to evaluate what the tests are testing.

### Principles for Vue Component Tests

_All global objects of a Vue instance must be mocked._
Those are for example `$route`, `$router`, `$t`, `$store` etc. Some of them can't be used as they are in a unit test environment, but also those which could, should not. This makes sure that the unit tests are independent of other implementations except the unit they are testing. Unit tests will become focused and easy to maintain. Changing one unit does not lead to failing tests of other units. Currently many test suites use the actual store. This comes with many downsides. Simply never use the actual store, always use the ability of the Vue test utils to provide a simplified store just for the component test.

_Use data generator functions._
Unfortunately it happened that we have now two concepts of getting test data. One are the static objects in `tests/unit/data/mock-data.ts`. The others are the generator functions in `tests/unit/utils/data-generator`. Only one of them should be used. Due to the preferences of the team members we agreed that data functions are the better solution for us. Static objects require us to create a new object for each kind of a case tests could need them. Each time a tester needs some data, he first needs to go through all already existing objects and check if what he needs already exists, else create a new one. This procedure depends on good, long and descriptive names of the different objects. If any object is not used anymore, this might get forgotten and the module starts to clutter. Generator functions have the advantage that each tester can go for them straight forward and tell them in a minimal manner what special property the test cares about for this only case. The call of this generator is after all the same as a long descriptive object. The code remains minimal and not needed "objects" are simply deleted when the test gets deleted. Furthermore are data generator functions a one time effort, while making the live of the tester easy.

_Always use createWrapper per test case._
Each test suite that is testing a Vue component must provide a `createWrapper()` function that is initializing the component for test purpose. This function is responsible for providing the component with all mocks it needs. Every property that must be changeable due to different test cases must be exposed as function parameter with a good default value. The wrapper instance of the component is then always created within each test case itself and is not a shared variable in the scope of the test suite that gets (partially) overwritten from case to case or via a hook function. This makes sure that test cases remain as independent as possible from each other, making sure no flakiness could be introduced. Adding or deleting tests can be achieved easily without requiring to know (all) other test cases of the suite. Furthermore does the call of the `createWrapper()` function now clearly show which changed properties of the component the case cares about and thereby automatically provides a better description of itself via code.

_We don't clutter the test suites._
A good test suite should read like `describe my-unit -> it should do a when b`. Everything that is necessary in terms of creating helper functions, creating test data instances, mocking stuff etc should take place either before the description starts or is part of a specific case. If something should be more dynamic or needs to be re-created/reset for each test case, this should be part of the `createWrapper()` function (e.g. get clean function spies, a pure store, ...). The usage of hook functions should be reduced to a minimum for unit tests. There should be rarely the case that a hook can do something better what the `createWrapper()` can't provide. The `createWrapper()` itself is itself a helper function that should be defined outside the description block.

_Always use shallowMount, never use pure mount._
The pure `mount()` function does not stub the children of a component. This leads to the problem that we first not isolate the unit correctly and second we need to satisfy the requirements of all children as well. This is one of the most annoying parts of writing a new test suite. Because the tester will aim for providing the wrapper with all mocks the unit needs. But then running the tests, one child component after another starts to complain about missing things, even the to test parent component does not have this dependencies as a unit. Satisfying all child components comes with even more disadvantages. If a child component changes, this can lead to failing tests of other units, since their test suites do not satisfy the new requirements anymore. Or the other way around, the cluttered test suites never get tidied up when a child components removes dependencies. After all this results into an awkward mix of unit and integration tests, making the daily live of developers a night mare.
Using `shallowMount()` stubs all child components. This means there is a stub element in the produced DOM of the component, without instantiating the child component (and thereby also not rendering it). There is "only" one downside to this approach: stubs are stupid. This means for example you can't actually click a stubbed Vuetify button. Therefore we need to do some research. One (partial) approach is that we unstub Vuetify components. This means telling the wrapper to stub Vuetify components with the components themselves. After all this just abuses the custom stub functionality. This is okay, since the components by Vuetify are no units in our system. So we do not need to test them. Also they are pure, meaning they have no external dependencies. Vuetify supports the "a la cart" usage. Means that we do not need to tell Vue to use Vuetify, but manually import only those components we need from Vuetify. This will require some configuration update of Jest, since it can't handle `.vue` file imports. Although not related to the tests, does the a-la-cart approach applied in the components themselves lead to a much smaller package size of the whole dApp. Finally we need to figure out how to work with our own components that get subbed, but need to emit events the parent component reacts to.

### Integration Tests

At the moment we kinda have some integrations tests due to our bad isolation of the unit tests. Following the above principles will lead to clean and good unit tests, but removes all test results/properties that fall into the category of unit integration. Integration tests in the dApp mean that components are used correctly within other components and globally injected plugins like the store or router. This is not a reason to not having clean unit tests. But it requires some attendance.
We agreed that we should start to improve our code linting and make it much more strict. Therefore we should do some research as well. This should make sure that for example the used getters of the store do really exist and the returned type is correctly expected. Therefore we also intend to improve the type saftiness of the store. Other parts like the `i18n` plugin are already covered well, telling us when a translation does not exist.

### Refactoring

While the above principles are related to the Vue components, we also have tests
for more "normal" code (in fact they don't need a library with a wrapper to
mount components etc). These include for example the router, the store or the
SDK wrapper. Some of their tests have become messy. We take this as an
indicator that the code that gets tested is not well structured anymore.
Therefore we want to refactor them and clean up the code. This then allows us
to have more focused tests that are easy to read. The router has become
refactored recently and can eventually be taken as inspiration. We will create
individual issues as action items to achieve these improvements:

- `RaidenService.ts` (issue to be opened, including details)
- `store/index.ts` (issue to be opened, including details)

### PR Checks

Having such a lot of tools that evaluate our code in PRs is a bless. Many projects don't have them and that is sad. We should understand why we have them there and why they are not our enemies (although some colleagues feel like it). Having so many tools supporting our daily development is reducing the load from the developer and reviewer. Machines should do what machines can do best and we as humans than add what they can not. Two of the most complained about tools are CodeCov and CodeClimate. In our meeting it helped to talk about what their task is and how we should react to their reports. Both tools must be seen in first place as a helper for keeping the project continuously "good" (sorry for not finding a better adjective).

So can CodeCov make sure that we always have a minimum of coverage, but during PRs its main responsibility is to give hints about too high fluctuation. If a developer adds new code, he might forgot to add tests for it. CodeCov will detect that by an increasing amount of not executed lines of code during the tests. If that is the case, the developer should be reminded to write tests for his new feature. If he did so and CodeCov still complains, he either does not test good enough or there is a good reason why not. The "not good enough" should be covered by the tolerance value of a dropping coverage. Means it is fine to be not perfect. But if the coverage drops heavily then the developer probably did a bad job in providing enough tests. CodeCov can help to show the developer which part of the code is not covered. Therefore it is easy to evaluate from here. Eventually there is a good reason why this is not covered. In our project this could be browser related functionally, that **can't** be tested within the unit tests. Then the developer and the reviewer can identify that and make as humans the decision that this coverage drop is "intended"/has a reason. Such decisions should be written down in the PR. Alternatively the developer can add a comment to the code, disabling CodeCov for it and putting a reason next to it. This will also save our overall statistics (which are just nice to present).
So CodeCov is supporting us to always do our best we can to test the application well with unit tests. We as smart humans always have the final decision what makes sense or not. Just imagine external contributors. We don't want to have the heavy work to make sure the contributor did a good job. Machines can tell him to improve and meet our standards before a human reviewer invests its costly time.
Also does CodeCov allow us to evaluate as humans if the tests are good on a higher level, being free in our minds to verify if they cover everything.
Finally it does not make sense to increase the thresholds too much. This just means we accept either worse test effort or we will miss to actively do decisions what is okay to not be covered. This is especially the case when we attempt to keep PRs small (which a topic on itself). Then the CodeCov would miss such mistakes more easily and is less helpful.

CodeClimate is pretty similar in many cases. So I'll keep this paragraph more short. In fact it makes sure that if we extend our code base over time, we still keep it maintainable. Over time things will grow. Modules, functions, the count of function parameters etc. At some point any new feature can hit a set limit. We need a limit because else we never take action. If nobody takes action the code gets out of control. Thereby any developer will then need to make sure the code remains good. This should be a continuous process. Tools like CodeClimate should be used from the very beginning. Thereby we never get a big report. Nobody wants to work on just all these reports at once. Big reports make the developers feel bad and they feel criticized. But doing small adjustments on each PR does not hurt feelings and costs less time at once.
And if there is a very good reason why the code must be as complex as it is or refactoring makes it worse to read/maintain, then the human developer can make the final decision, write down the reason and merge PR with the agreement of the reviewer, although CodeClimate reports issues. It is a machine that can't evaluate the code on a higher level.

**Comment by weilbith** [comment]
I was not able to make the Vuetify a la Cart working with Jest so far. Since the main task of this issue is done and I don't want to have this issue lying around while working on more urgent stuff, I opened [an issue](https://github.com/raiden-network/light-client/issues/2234) for that. Else every tester can take the `tests/unit/components/token/*` test files as inspiration. They already follow most of the principles here. Although they are not yet perfect, suffering from the Vuetify stub issue.
