### ISSUE TITLE
Change from sections to tabs in overviews (tokens and channels)

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#221]
## Description

Currently we have divided tokens and channels in different process steps within horizontal sections. This is getting changed to tabs.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
As a comment on this transition, it's important that the user doesn't miss items which may be in other tabs because they're hidden. A possibility is to have a badge/counter on the left or right of each tab so the user is always aware of how many items are in other tabs. A possible approach as well would be to additionally have an `All` tab as first/pre-selected tab, and use the new tabs as **filters** instead of hidding everything else than first by default.

**Comment by christianbrb** [comment]
Closing as it seems, that we go for another approach
