### ISSUE TITLE
Nonce mismatches for LockedTransfer message

### ISSUE THREAD

**Issue by ezdac** [raiden-network/light-client#2229]
I am still getting Nonce mismatches when using the dApp to do direct transfers with a Raiden python node.
Corresponding Python Raiden node log entry:

``` json
{
  "node": "0x11faFfcc7Aa31d731a8Cf6e998216731ed78D7AF",
  "raiden_events": [
    {
      "reason": "Invalid LockedTransfer message. Nonce did not change sequentially, expected: 3 got: 1.",
      "payment_identifier": "3893759327999191202",
      "_type": "raiden.transfer.events.EventInvalidReceivedLockedTransfer"
    },
    {
      "secrethash": "0xd50a1a8df7508f769964be2a384b8bb0cb39f9e7b0fcb04c3dd272ee7397953c",
      "reason": "Invalid LockedTransfer message. Nonce did not change sequentially, expected: 3 got: 1.",
      "identifier": "3893759327999191202",
      "_type": "raiden.transfer.mediated_transfer.events.EventUnlockClaimFailed"
    }
  ],
  "event": "Raiden events",
  "logger": "raiden.raiden_service",
  "level": "debug",
  "greenlet_name": "GMatrixClient.message_worker user_id:@0x11faffcc7aa31d731a8cf6e998216731ed78d7af:transport.demo001.env.raiden.network",
  "timestamp": "2020-10-12 08:01:00.921479"
}

```

## Steps to Reproduce
1. Used the `lightclient.raiden.network/staging` across several versions, clicking the refresh button on version updates
2. Due to previous nonce mismatches closed a channel with transaction partner.
3. Opened a new funded channel with transaction partner node (Raiden Python 1.1.1) on Goerli.
4. Did one direct transfer that succeeded, closed the dApp immediately
5. Tried another direct transfer, that gets retried on the dApp side and remains pending, while messages are being ignored on the transaction partner side due to nonce mismatches.

No version refreshes were conducted on the dApp side between steps 3. and 5.

## Expected Result
- Transfers should succeed, state should be persisted immediately in the dApp, even though the dApp is closed after successful transfers.

## Actual Result
- Pending transfer on sender side / rejected message on receiver side due to lower nonce on a transfer after closing and re-opening the dApp.

## Additional Infos (Optional) 
```
- Google Chrome (Version 85.0.4183.121)
- MacOS 10.15.7
```

[raiden_0x68aD5215b1791E5608bcf825477af114B799022D_2020-10-12T08_02_01.869Z.log](https://github.com/raiden-network/light-client/files/5363808/raiden_0x68aD5215b1791E5608bcf825477af114B799022D_2020-10-12T08_02_01.869Z.log)

[raiden-debug_2020-10-12T07:44:28.131240.log](https://github.com/raiden-network/light-client/files/5363816/raiden-debug_2020-10-12T07.44.28.131240.log)

**Comment by ezdac** [comment]
Update:
I am also getting this after using a completely new Subkey and base account, after 16 successfully sent `LockedTransfers`. Note, that I could be closing the app quickly after / during the successful transfer notification popup shows.

**Comment by andrevmatos** [comment]
Ok, this issue is in our side. I've seen it before while debugging and implementing #2174. Looks like a bug has been triggered by some weird behavior possibly on matrix client library, where **only when** using room messages/invites system, it enters some form of infinite loop or thrashing, which slows down **a lot** the event loop handling and callbacks, making RxJS, epics and even normal callbacks take an increasing amount of time to be processed. This seems to have caused the persistence middleware to not be able to save your request on time. This **does not** happen between light-clients, because this bug isn't triggered there. I'm working on a reliable way to trigger this, and to fix it. The persistence layer itself, matrix & RxJS seems to be correct, but we need to identify the cause of this weird behavior and fix it.
