### ISSUE TITLE
Message to update the dApp does not appear

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2382]
## Steps to Reproduce
1. Access the dApp on staging
2. Merge a new PR on master

## Expected Result
- I am getting a message, that I need to click to update the dApp

## Actual Result
- I am not getting the message

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by christianbrb** [comment]
@weilbith 
How is our caching currently working? I was under the impression, that in the past we have completely cached the dApp and only refreshed on a new build. I think this would be already sufficient.

![grafik](https://user-images.githubusercontent.com/35398162/99941306-18c2bc80-2d6e-11eb-88ef-561d72122310.png)

**Comment by weilbith** [comment]
Yes, there is something about caching due to a service worker. I wasn't in touch with that functionality, nor have I used such for GitHub pages before. I'll investigate into the details.

**Comment by christianbrb** [comment]
Here is the original commit from @nephix 
https://github.com/raiden-network/light-client/commit/0f33983dcb24da72181aa96aa502a96bc77d9219#diff-8c64b93ec8d00cd50d1fdb31130cbc7556d80436ada727aef1a73c9c9c280555

**Comment by christianbrb** [comment]
As I seem to get the latest updates silently I have classified the bug as medium.

**Comment by weilbith** [comment]
>  Access the dApp on staging
    Merge a new PR on master

:joy:

**Comment by weilbith** [comment]
Alright, I should give a status update.
The current state is that it is working already. Nothing has changed on our side or GitHub. Also the DNS zone file is fine. The issue is made by the additional security mechanisms of Firefox. If you start Firefox in plain mode (`firefox --ProfileManager` to create such independently), this just works fine. In Chrome or other browsers it also just works out of the box. But there I have no further settings which I could try since only Firefox is my browser for daily usage.
Unfortunately I was not able to determine how to circumvent this issue or which exact setting is causing it. It seems to be related to some more restrict cross origin policies. But I just can't find where this should get loaded.

But the offline version is not working. The service worker is apparently not doing this correctly.
I also did the PWA check in the Chrome browser and we have to improve some things. I need to check which are required, but the biggest issue next to the offline feature is the performance. The package is just too big.

**Comment by weilbith** [comment]
@christianbrb I would like to close this issue. I think it is not worth to waste more time in making it working for this specific setup. Also it hurts, since it affects myself as well. But we have some time constraints.
I will open a new issue to tackle the rest of the PWA stuff like making the offline stuff working etc.

**Comment by weilbith** [comment]
@christianbrb please re-open this issue if you still want to tackle this. This could be interesting to do after mainnet release.

**Comment by weilbith** [comment]
Ah, while working on the caching part, I think I found the security issue. The PWA plugin which is just an interface to Webpack it's Workbox plugin uses this external source: https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js

**Comment by weilbith** [comment]
Maybe the `anonymous` options helps (Mozilla [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-crossorigin)). Unfortunately we can't test this without a release.
