### ISSUE TITLE
Editing ether value in the Transfer Eth screen gets white out in LC mobile

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2422]
## Steps to Reproduce
https://github.com/raiden-network/light-client/issues/2400#issuecomment-734294170 

## Expected Result
- The ether amount being entered by the user should be visible to him 

## Actual Result
- Transfer eth screen the amount is not visible when editing it. Its gets white out due to the background.
![transfer_eth_screen](https://user-images.githubusercontent.com/15123108/100453094-62016c00-30e0-11eb-9997-a8ca36337c1a.jpeg)

**Comment by weilbith** [comment]
Okay the root of this issue is that the view-port size changes when the keyboard comes in. And as the very top level element `application-wrapper` is bound to the size of the view port, this causes the trouble.

**Comment by weilbith** [comment]
I just had a talk with Talel and this might will also fix #2421. His PR will remain open until we know if the more generic solution that is required for this issue here will also solve his problem. And as his solution is a local one only, we could close that PR and replace it with mine for both issues.
