### ISSUE TITLE
Token switched when leaving 'channels' screen

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2430]
## Steps to Reproduce
1. Select a token that's not first in the token list
2. Go to the channels list
3. Click the 'back' button

## Expected Result
- Should be back on overview page for the selected token

## Actual Result
- The first token from the token list is shown in the overview page

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by weilbith** [comment]
Hmm okay the issue is that the button does not work like the browser back button but directly navigates to the transfer route. Without any route parameter this will automatically select the first token. Other buttons work correctly (e.g. account or notifications). So I'll first check if we can re-use this. Else we need to persist the currently in-use token to recover that information.

**Comment by weilbith** [comment]
Okay it looks like we can get away without extending the applications state, but just improving the functionality of the back button (which is the same for all routes). I'll open the PR as soon as the tests are fixed.
