### ISSUE TITLE
Error trying to fetch PFS info for Hub list

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2462]
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- The hub list does not get fetched correctly.
`GET https://pfs-goerli-with-fee.services-.raiden.network/api/v1/info net::ERR_NAME_NOT_RESOLVED`

Somehow SDK constructs this address wrongly 
**pfs-goerli-with-fee.services-.raiden.network**

![hub_list_fetch_issue](https://user-images.githubusercontent.com/15123108/102887397-e4314600-447c-11eb-98a4-51a6fb195294.png)

**Comment by andrevmatos** [comment]
It works for me:
![image](https://user-images.githubusercontent.com/587021/102890611-7dd80380-443b-11eb-8982-5ce1242aef0d.png)

The error you see there isn't SDK's fault. Some PFS is registered with invalid domain name, which isn't a problem. The SDK tries to fetch its info, handles the exception and proceeds to try the next PFS in list.
Please, try again with a fresh subkey (on another localhost IP, e.g. https://127.0.0.2:8080), an issue caused by our development/staging environments having moved to `transport0x` servers may be preventing some PFS on clients with state initialized on the old demo001 env may be the cause of this issue, but a fresh state should be able to properly fetch the suggested partners array.

**Comment by agatsoh** [comment]
Ok i will give it a try, with `https://127.0.0.2:8080` but `https://localhost:8080` does not work on multiple browsers for me.

**Comment by agatsoh** [comment]
@andrevmatos so I tested this on two things 
while starting the dApp server locally I get this 

App running at:
  - Local:   http://localhost:8080 
  - Network: http://192.168.29.50:8080
  
  So i went ahead and used 
  `http://192.168.29.50:8080/` 
  `http://127.0.0.1:8080/`
  Both the times its the same error as above. 
  
  
![hub_fetch_127 0 0 1](https://user-images.githubusercontent.com/15123108/102892731-522e3b00-4486-11eb-8ed2-086d28a71f5a.png)
