### ISSUE TITLE
I want to enable the hub to close (and settle?) my channel

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#250]
## User Story
As Chris I want to enable the hub to close (and settle?) my channel so that I don't have to do it

@andrevmatos Did I understand that correctly? Reference is https://github.com/raiden-network/raiden-contracts/issues/1123

**Comment by andrevmatos** [comment]
That's not exactly for the hub. HUB can always close and settle whenever they want. The issue is about having generic 3rd-parties **willing** to pay for the gas, to do so, through an off-chain signature from us. The main use-case is #172 , where the main account (seen as a 3rd-party from contract's perspective) pays for the gas instead of the eth-less subkey. Other possibilites may arise as well, like companies willing to pay for the first couple of on-chain txs for users for easy onboarding, but strictly speaking, if the user wants to close, they're the one willing to pay for the gas, not the hub.

**Comment by christianbrb** [comment]
Thanks for the explanation :-) Closing it
