### ISSUE TITLE
Redeploy the Hub with updated configurations

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2513]
## Description
Make Hub work again.

## Acceptance criteria
Hub should run with the most recent Python client, use a Geth node and the latest version of the PFS.

## Tasks
- [ ] Bump Python client image version to most recent version
- [ ] Use Geth node

**Comment by weilbith** [comment]
The update is currently stuck. We did an update, but the used Python client for the Raiden node is stuck in an endless restart loop. The initial sync phase always fails because of the missing database. This has not happen before as the hub was in a "special" state.
We had a meeting including a member of the PC team. We agreed on a solution to fix the bug. Paul will implement this fix (I'll link the PR here). When the PR gets merged there will be an automated Docker image build that is available at DockerHub. Note that this won't be an actual release. So we will need to use the exact hash of the image as reference for the moment.  If the image is available we will do another update of the hub. 
Furthermore we have agreed to make the database of the hub persistent. Also this should be handled better by the PC we should keep the database to avoid many other potential issues. I'll create an issue for this task.

**Comment by weilbith** [comment]
This is blocked again. On last Friday we had another issue with the PC. This is under discussion now.

**Comment by weilbith** [comment]
All related PRs are merged and hub is running again.
