### ISSUE TITLE
Staging LC picks up PFS's from the disjoint RSBs at random

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2521]
## Steps to Reproduce
Environment setup:
node1(LC) <----> hub(python client) <------> node2 (LC)
1. establish bi-directonal channels between node1 and hub, node2 and hub
2. Hub has been specifically configured to run on the following 
   2.1 PFS on `pfs.demo001.env.raiden.network`
   2.2 Transport on `transport.demo001.env.raiden.network` 
3. Node1 and Node2  select the 
    3.1 Transport as `transport.demo001.env.raiden.network` but 
    3.2 PFS they sometimes select 
           3.2 a `pfs.demo001.env.raiden.network` and this is time when the tranfer has correct route and the transfer goes through. At the time the nodes dont see the other PFSs and act as if  `pfs.demo001.env.raiden.network` is the only PFS available. Unfortunately i did not take a screenshot for this.
           3.2 b Sometimes the nodes use all the other PFS's like `pfs.transport0x.raiden.network` (where x is a number) but do not see the `pfs.demo001.env.raiden.network` as if it never exists.

![node1_disjoint_pfs](https://user-images.githubusercontent.com/15123108/105344810-6e4e0500-5c09-11eb-8ed7-291f7a8fea6f.jpg)
The next step they get `No route between you and target`
![no_route_disjoint_screen](https://user-images.githubusercontent.com/15123108/105344825-7312b900-5c09-11eb-929a-8bda0d3cf854.png)

This causes one way transfers even though capacity exists either way. 
Lots of users on gitter are facing the same issue and are utterly confused why they cannot make a simple transfer and why the hub is always offline or something which can happen when **hub** is on `transport.transport0x.raiden.network` and `pfs.transport0x.raiden.network` 

                         

## Expected Result
- Each time depending on the transport server that has been picked up the correct PFS should be picked up.

## Actual Result
- Has been described above

**Comment by agatsoh** [comment]
Observations using local LC nodes as opposed to the staging ones
using the staging environment file `.env.staging` for locally deployed nodes
`yarn workspace raiden-dapp run serve --mode staging`
1. the nodes pickup `transport02` server for transport and query all the PFS's at the time of route selection.
2. The hub needs to be on the `transport0x` servers otherwise the again we would get `No route between you and the target` above.

Finally if we use a environment file for example like this 
```
VUE_APP_PFS=https://pfs.transport02.raiden.network
VUE_APP_MATRIX_SERVER=https://transport.transport02.raiden.network
VUE_APP_HUB=hub.raiden.eth
VUE_APP_ALLOW_MAINNET=false
VUE_APP_IMPRINT=https://raiden.network/privacy.html
```
and start the servers
`yarn workspace raiden-dapp run serve --mode testnet`

in this way the PFS selection is forced in the dapp to use only that one PFS which we have specified in the environment file.

![LC_testnet_env_pfs_forced](https://user-images.githubusercontent.com/15123108/105859370-71366480-6012-11eb-9728-08a68000a8bb.png)


I reach the conclusion that till we have this disjoint transport servers with staging environment not explicitly specifying a PFS this confusion is there to remain 
@talel

**Comment by taleldayekh** [comment]
@weilbith Describe issue and our solution to the problem.

**Comment by weilbith** [comment]
Alight, let's give this a try.

The root of all the described symptoms is that while the `development` and `staging` environment share the same contract deployment, their associated RSB deployments are different.  Thereby we get an awkward 50% connection of both environments.

In our discussions we pointed out two possible solutions. Either make both fully connected (100%) or completely separate them as two (0% connection). Merging both environments completely seems to be a bad idea as they have different purposes. The staging environment is meant to be used for test network demonstrations of the Raiden clients. As a environment for external developers to try the system and get familiar with the libraries to build their own products on top. Therefore it is meant to be stable and reliably working. Though it has not as strict reliability constraints as the mainnet.
The development environment is meant to be used for internal engineering. Basically the step after the end-to-end tests, like for the Scenario Player. An environment where the RSB is always on latest version. Where unstable/unreleased features of the services can be tested. Thereby it is less stable and reliable than the staging environment. But all eventual issues stay internal and only hinder our own daily development flow. Deployments can be way less formal and hacky if necessary. 

Therefore it is the currently favored approach to separate both networks. As the stable version the staging environment should stay as is and the development environments pops out. This requires us to

- make a new contract deployment on Goerli
- the current active services for the development need to change their contract pointers and probably a fresh state
- all client configurations related to the different environments need to adopted

The following steps on this topic are:

- align on the decision and solution approach
- complete the task list
- decide if each client implementation needs its own development environment
- create actual issues for the tasks in the list
- assign issues and prioritize them in the imperative order

---

@palango @andrevmatos could you eventually provide some feedback, especially regarding the task list, as I'm not familiar with the Raiden service bundle.

**Comment by palango** [comment]
Looks good to me, I think it's important to first align on the approach, we can work out the details afterwards.

**Comment by andrevmatos** [comment]
I think that should be about it. Some observations:
- I'd like the clients to continue using the same network, it makes it easier to cross-test. 
- at least on LC, the state key/db/name uses contains the TokenNetworkRegistry address, so a new deployment automatically generates a new state
- Please, let's try to re-use as much contracts as possible; e.g. at least the tokens and service token contracts can be reused without issues, and save us calls to mint them again.
  - Maybe SecretRegistry is safe to be reused as well.
- the clients (at least LC) picks automatically the goerli addresses from the JSON file from the `raiden-contracts` repo. I think the file there should remain pointing to the _stable_ deployment, but then we need to ensure that the right contracts are used on development/staging servings of the LC and PC. The LC supports auto-detecting the addresses from a single entry-point contract (UDC address), we just need to expose this on dApp to pick from the env vars, and have them set in the development/staging `.env`s.

**Comment by weilbith** [comment]
> Looks good to me, I think it's important to first align on the approach, we can work out the details afterwards.

@palango who would you suggest to take into account. So we could just mention them here.

> Please, let's try to re-use as much contracts as possible; e.g. at least the tokens and service token contracts can be reused without issues, and save us calls to mint them again.

Good idea. Should be safe to re-use the tokens from my perspective. In my opinion they are actually not part of the Raiden contracts themselves.

> The LC supports auto-detecting the addresses from a single entry-point contract (UDC address), we just need to expose this on dApp to pick from the env vars, and have them set in the development/staging .envs.

Yes. I remember. We just have to do it. :grimacing:

**Comment by weilbith** [comment]
@eorituz @ezdac @karlb @ulope could you have a look [from here](https://github.com/raiden-network/light-client/issues/2521#issuecomment-776580907) and provide some feedback? We could also schedule a meeting if the opinions diverge too much or there are many questions.

**Comment by karlb** [comment]
> I'd like the both clients to use the same network, it makes it easier to cross-test.

I agree.

> * Maybe SecretRegistry is safe to be reused as well.

It is and there are plans to reuse it even on mainnet for a long time: https://github.com/raiden-network/raiden-contracts/issues/1182

> e.g. at least the tokens and service token contracts can be reused without issues

Reusing the tokens is definitively a good idea and has been advocated multiple times already. It would cause less confusion and make the testnets more similar to the mainnet, since the mainnet also uses the same tokens on each deployment. The necessary changes to the deployment have just never been done.

**Comment by karlb** [comment]
Using different contract deployments will provide a nice clean split. Coordinating the contract changes across all the different repos could be error-prone, though. Does anyone have a clear view on how that would work in detail, yet?

**Comment by taleldayekh** [comment]
@taleldayekh organise meeting about this.

**Comment by karlb** [comment]
Another approach would be to reject PFSs that are not operating in the same federation (we could add a federation id to the info endpoint if the existing info is not sufficient) and look for another PFS. That behavior is useful anyway and would avoid the need to add any new configuration. This would be less prone to strange errors due to misconfiguration.

**Comment by konradkonrad** [comment]
I would suggest to move the demo environment to rinkeby.

Pros:
- completely separate deployment
- no extra code necessary
Cons:
- don't know?

**Comment by karlb** [comment]
I just checked that the contract deployment on rinkeby is up to date. So we could start using rinkeby for the demo env right away.

**Comment by karlb** [comment]
Counter-argument from @eorituz:

> Isn’t there another way than moving the demoenv to another network? This will kill all services, demos and applications running on demoenv
>
> It would also require to redeploy tokens/set new tokens and funds nodes….

**Comment by eorituz** [comment]
My suggestion would be to move the LC away from demoenv and use a newly deployed "testenv".
The demoenv would stay as it is and all demos keep on working. (The idea of the demoenv was to be as long living as possible and only update it if raiden has major updates/improvements)
Also, we could prevent this conflict of interest for future occurrences.

**Comment by andrevmatos** [comment]
This is not about LC. The "stable" LC uses is expected to continue using the `demoenv`. The "unstable"/staging LC is expected to stay on the PC's testnet (`transport0*`). It's more about ensuring these two networks either can talk properly, or are fully disjoint (by e.g. moving the testnet to a new contracts deployment). The specific issue here should also happen on PC, if for any reason it tries to talk to `hub.raiden.eth` node or the maybe pick the demoenv's PFS. It only got detected first on the LC because we have specific environments using each of them, and also hardcode/defaults to suggesting the this HUB on our deployed instance.

I think, since the demoenv is currently being used outside BB, we should move the PC + LC testnet (`transport0[1-5]`) matrix & services to a new Goerli contracts deployment, leaving the current network only for demoenv.

**Comment by konradkonrad** [comment]
> I think, since the demoenv is currently being used outside BB, we should move the PC + LC testnet (transport0[1-5]) matrix & services to a new Goerli contracts deployment, leaving the current network only for demoenv.

Yes, here is my proposed course of action:
- [ ] create a new goerli contract deployment with the codename `unstable`, that's to be used with `transport[1-5]`, internal scenario player, PC & LC testing
- [ ] Introduce a special case chain id, `GOERLI-UNSTABLE`, to the contract manager for selecting this deployment.
- [ ] Add a configuration value for PC (LC, too?): `--development-environment [demo (default) | unstable]`. The default, `demo`, will point the client to the existing services contract using the known mechanism. The `unstable` setting will use the new contract deployment by means of using the special chain id from above.
- [ ] Update CI infrastructure (i.e. scenario-player) to use the `--development-environment unstable` flag.
- [ ] If there ever is an update to the ["stable" demo docker container](https://hub.docker.com/layers/raidennetwork/raiden/demoenv001/images/sha256-d6df1b8cf72401c2767d12c32fbd18246176dd47360b1550265925016c5c8c4e?context=explore), that is build on more recent PC code, we **must** also update the demo deployment. In other words move to a `demoenv002`. This is due to the changes in the services communication model, [switching to `toDevice` chatter to registered service addresses](https://github.com/raiden-network/raiden/issues/6813).

This should avoid any breakage of existing demos and prevent future spillover.

**Comment by karlb** [comment]
The new contracts are set up and used in the services-dev services and the services on transport05 as well as by the SP CI development.json environment.

Remaining TODOs:
- [ ] Update services on transport01-04 to use these contracts
- [ ] Allow LC to use these contracts
- [ ] Configure LC to use these contracts when run in SP CI
- [ ] Demo env and `development_environment: unstable` work. Service discovery does not work in demo env, but is also not used, usually. Decide if that is enough.
- [ ] Update docs if neccessary

**Comment by taleldayekh** [comment]
Can we close this ones our `next` branch has been merged to master? @taleldayekh

**Comment by taleldayekh** [comment]
Closing, `next` is noe merged to `master`.
