### ISSUE TITLE
Mainnet smoke test

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2561]
## Description

We want to do some first, simple mainnet testing.

## Tasks
- [x] Measure sync performance
- [x] Open 2 channels
  - [ ] Save logs
- [x] Send direct and mediated transfers

### Timings for initial/subsequent syncs
- Metamask: ~17s
- BB mainnet geth node: ~800s
- Andres node: ~45s

Subsequent syncs aren't substantially faster than the initial sync: https://github.com/raiden-network/light-client/issues/2566

**Comment by agatsoh** [comment]
Ok finally leaving my testing results for 2 nodes with a channel here 

LC browser node
===================
`0x9307b1EE0f1299547F8F46A268efbd6089Ce81B2`
subkey account: 0x07d036DbC602F0191a4bC8e217fe48d34cD4a230
Initial  synch for fresh account: `6136` ms

DAI Address
0x6B175474E89094C44Da98b954EedeAC495271d0F

Summary of all  spending on the LC Browser node can be found [here](https://docs.google.com/spreadsheets/d/1gVf35cGrBZgOOX_iUMlXwvJLVY45ZLGctNRzUrUpH9E/edit?pli=1#gid=2093499663) 

Made 4 direct transfers which became faster over time with each transfer.

**273ms**
**225ms**
**211ms**
**183ms**

LC browser logs
----------------------------
[raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-02-25T10_45_14.018Z.log](https://github.com/raiden-network/light-client/files/6107861/raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-02-25T10_45_14.018Z.log)
[raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-02-24T13_18_23.400Z.log](https://github.com/raiden-network/light-client/files/6107862/raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-02-24T13_18_23.400Z.log)
[raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-02-24T08_57_57.881Z.log](https://github.com/raiden-network/light-client/files/6107863/raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-02-24T08_57_57.881Z.log)



LC CLI node
=================
`0x5d3c715dfec88ee0C1a14C2B6ed3b0878612581c`
Does not have any funds in ETH or any other coin till date

I started the LC node in two ways and then stuck to the 2nd 

```
node build/index.js --pathfinding-service-address=https://pfs.transport.raiden.overdoze.se --matrix-server=https://transport.raiden.overdoze.se --eth-rpc-endpoint http://10.104.6.7:8545 --api-address "http://localhost:5010" --keystore-path /home/devaki/.ethereum/keystore/ --address 0x5d3c715dfec88ee0C1a14C2B6ed3b0878612581c --log-file node-5d3c71-mainnet-24thFeb2021.log --password-file password_file.txt --accept-disclaimer --enable-monitoring
```

```
node build/index.js --eth-rpc-endpoint http://10.104.6.7:8545 --api-address "http://localhost:5010" --keystore-path /home/devaki/.ethereum/keystore/ --address 0x5d3c715dfec88ee0C1a14C2B6ed3b0878612581c --log-file node-5d3c71-mainnet-8thMarch2021.log --password-file password_file.txt --accept-disclaimer --enable-monitoring
```

Querying API of CLI Node:
--------------------------------------

* Query about the node itself, kind of a healthcheck
`curl -i http://localhost:5010/api/v1/address`

* Query about the channels of the node
```
curl -i \
http://localhost:5010/api/v1/channels/0x6B175474E89094C44Da98b954EedeAC495271d0F/0x07d036DbC602F0191a4bC8e217fe48d34cD4a230
```

* Making one DAI payments through the node
```
curl -i -X POST \
http://localhost:5010/api/v1/payments/0x6B175474E89094C44Da98b954EedeAC495271d0F/0x07d036DbC602F0191a4bC8e217fe48d34cD4a230 \
-H 'Content-Type: application/json' \
--data-raw '{"amount": "1000000000000000000"}'
```

Did several transfers but could not decipher the payment times due to encoding in the log files but I am attaching logs so that would make it clear. Its mostly something like this
33m222274
33m0
33m1
33m5473

LC CLI logs
---------------------------------------
[node-5d3c71-mainnet-24thFeb2021.log](https://github.com/raiden-network/light-client/files/6107849/node-5d3c71-mainnet-24thFeb2021.log)
[node-5d3c71-mainnet-8thMarch2021.log](https://github.com/raiden-network/light-client/files/6107850/node-5d3c71-mainnet-8thMarch2021.log)

**Comment by palango** [comment]
Did a successful run of BF1 on mainnet again.
There was a disconnect of the SP from the geth node, but I could restart it and then it finished successfully.

See also https://github.com/raiden-network/team/issues/896
