### ISSUE TITLE
dApp mobile: Ramp Network integration research

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2603]
## User Story

As Chris I want to purchase crypto without leaving the dApp by using third party services/apis like, i.e. Ramp Network.

## Acceptance criteria

Clear idea of the desired outcome of integrating i.e. the Ramp Network and a good estimation of the efforts required.

## Tasks

- [ ] Prepare initial research for future discussions

**Comment by weilbith** [comment]
Writing down the results, including the talk I had with Talel.

The RampNetwork can be integrated in two different ways:
1. Link
   - just a plain URL (maybe hidden behind a button) that will be opened in the users web-browser
   - can/will be provided with helpful parameters like the users Ethereum address, tokens pre-selection, ...
   - works basically exactly like we have integrated Uniswap right now to by SVT/RDN
   - we must not care at all about a users interactions and the transaction status
   - most simple solution possible with basically no work implementation wise (except some design stuff?)
   
2. SDK
   - add their npmjs.org package as dependency to our project
   - the user (kinda) stays in the dApp itself, but interacts with an iframe that pops-up (dApp gets shaded in background)
   - we can't customize anything in this modal, but the parameters as for the URL can be still specified
   - we will need an API token to have all payment methods available, not just Open Banking (takes 24-48h)
   - the user can cancel and re-open it any time, without switching the application
   - we get events by the modal what the user does, such are like cancelling, successful close with transactions, ... we can then extend the app to adopt the flow in regards of that (e.g. stay on the page when the user cancels [but he can continue from here himself] or auto-forward when closed successfully)
   - on a successful transfer we get an ID back, their API can be polled to get the transactions status (transactions can take up to 48h depending on the payment method) and shown to the user
   - way more work especially the event handling, data persistence, status polling, ...
   
Approach #1 should be probably the first version of the integration (maybe while waiting for the API key?)

Questions:
  - do we want to implement #2 at all?
  - should we put this into the onboarding flow and/or also somewhere in the general UI to allow re-buying when needed (maybe for each supported token on the token screen, but where to put the ETH stuff [account page?])
  - the user can only purchase one asset kind at a time, but usually needs at minimum 3 (while SVT/RDN are not supported here...), how to make this usable, especially in the onboarding flow?
  - RampNetwork advertise to co-operate with them to add custom tokens (RDN?!) are we interested?
  - do we want to have a place where to show the user the status of his last RampNetwork transaction (because where else should he look it up?) and should we store a history?
  
The major work here will be the integration into the UI and the user flow. The actual technical implementation isn't too complicated. Only the transaction status management and the different flows for the modal events are interesting.
