### ISSUE TITLE
LC browser node does not detect that a channel has been opened with it unless it is reloaded

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2617]
## Steps to Reproduce
1. Open a direct channel with a fresh LC node on the browser 
2. 

## Expected Result
- If a channel has been opened then it should detect it and go to the transfer screen

## Actual Result
- The LC browser keeps circling between the 
1. Available Tokens screen
2. Select Hub screen

**Comment by weilbith** [comment]
@agatsoh Talel and l are not sure if we get this issue description correctly. So the last part of the actual result section is a link to  #2607 which handles the endless loop navigation. There is an open PR for it. The question is if it does also resolves your issue here. So I just tried it out and if you open a channel and complete it with all transactions, it just closes the loading modal and navigate automatically back to the transfer screen. And if you decide to break up the channel open, then you can just use the back button to do so. Could provide some more details on your exact issue or just try the fix in #2623

**Comment by weilbith** [comment]
Okay, so we had discussed this with Sohan and the result was that he actually wants to have the auto-detection of externally opened channels. The currently behavior of a test shows that it will switch from the "no-tokens" state to "no-channel-open" state. This is caused by a missing token section, which is simply not possible in the "no-tokens" state, but must take place during the state change.
