### ISSUE TITLE
Update geth and synapse in e2e image

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2634]
The E2E image uses outdated versions of `geth` and `synapse`. We need to update them in order to test on an environment that is close to the one in which the LC will run.

## Tasks
- [ ] Update `geth` to Berlin-compatible version
- [ ] Update `synapse` to the version used in the RSB

**Comment by agatsoh** [comment]
We must upgrade the Geth version to `1.10.1` or later since goerli already upgraded to on `17th of March 2021` according to [this](https://blog.ethereum.org/2021/03/08/ethereum-berlin-upgrade-announcement/) post

**Comment by agatsoh** [comment]
The RSB [RC2](https://github.com/raiden-network/raiden-service-bundle/releases) has upgraded synapse to `v1.27.0` but we are still using  `v1.19.1`.

**Comment by palango** [comment]
> The RSB [RC2](https://github.com/raiden-network/raiden-service-bundle/releases) has upgraded synapse to `v1.27.0` but we are still using `v1.19.1`.

See also https://github.com/raiden-network/raiden-service-bundle/issues/261

**Comment by agatsoh** [comment]
@palango Ok they havent released but since they upgraded to `1.29.0` we should too.

**Comment by agatsoh** [comment]
@palango the build version [here](https://github.com/raiden-network/raiden-service-bundle/blob/master/BUILD_VERSIONS) shows `1.27.0` but our guide [here](https://github.com/raiden-network/light-client/tree/master/e2e-environment#transport) tells us to look out for the `BUILD VERSION` anyways will go with latest since raiden already upgraded. Unless someone has other opinions.

**Comment by palango** [comment]
> @palango the build version [here](https://github.com/raiden-network/raiden-service-bundle/blob/master/BUILD_VERSIONS) shows `1.27.0` but our guide [here](https://github.com/raiden-network/light-client/tree/master/e2e-environment#transport) tells us to look out for the `BUILD VERSION` anyways will go with latest since raiden already upgraded. Unless someone has other opinions.

Sorry, I don't understand what point you're trying to make. Can you explain it differently?

**Comment by agatsoh** [comment]
The RSB [BUILD_VERSIONS](https://github.com/raiden-network/raiden-service-bundle/blob/master/BUILD_VERSIONS) file has a version of synapse that is `1.27.0` but raiden as you already posted has upgraded synapse in their requirements [file](https://github.com/raiden-network/raiden/blob/develop/requirements/requirements-ci.txt#L357). and our [guide](https://github.com/raiden-network/light-client/tree/master/e2e-environment#transport) for running the the E2E tests tells us to look at the `BUILD_VERSIONS` file of the RSB. I hope there is no conflict in that.

**Comment by palango** [comment]
> The RSB [BUILD_VERSIONS](https://github.com/raiden-network/raiden-service-bundle/blob/master/BUILD_VERSIONS) file has a version of synapse that is `1.27.0` but raiden as you already posted has upgraded synapse in their requirements [file](https://github.com/raiden-network/raiden/blob/develop/requirements/requirements-ci.txt#L357) to `1.29.0` and our [guide](https://github.com/raiden-network/light-client/tree/master/e2e-environment#transport) for running the the E2E tests tells us to look at the `BUILD_VERSIONS` file of the RSB. I hope there is no conflict in that.

Yes, in my opinion we should update to 1.29 directly.

**Comment by agatsoh** [comment]
My findings uptil now:
Basically the issue boils down to breaking changes related to `broadcast` rooms,  `to_device` messages for services and many other breaking changes  which the python client have introduced. Its difficult to find the version of services and the RSB(for the `room_ensurer.py` and other setup scripts that we use) in sync with the the raiden version. Until there is some kind of uniformity in the `raiden`, `raiden services`, `RSB` versions that we say ok these `versions` of software work in sync together it would be difficult integrate the geth and synapse changes till then. Somebody who has indepth knowledge about actually what went in which commit and simulataneously in all the `raiden`, `raiden services` and `RSB ` could actually do this. But someone not so familiar would find it quite difficult. Also that we have breaking changes in the next branch might also be an issue here because the raiden python straightaway introduces breaking changes in their repo and we are much more careful so we need to also think which branch our `e2e` tests would run against.
@taleldayekh @palango @weilbith Just tagging you since you know these kind of issues much better than me. Would also like your valuable opinion here.

**Comment by taleldayekh** [comment]
Wait for PC release before continuing on this.

**Comment by palango** [comment]
Will be taken care of in https://github.com/raiden-network/light-client/issues/2699
