### ISSUE TITLE
dApp: Transfer screen header is being displayed on select token screen

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2675]
## Todo
Create a separate route specifically for this entry point to the dApp.

## Steps to Reproduce
1. Connect to the dApp with no previously connected tokens

## Expected Result
- Select token header

## Actual Result
- Transfer header

## Additional Infos (Optional) 
<img width="635" alt="Screenshot 2021-04-19 at 11 32 33" src="https://user-images.githubusercontent.com/43838780/115214780-26a12180-a103-11eb-8b7f-172384c282b2.png">

**Comment by weilbith** [comment]
We have discussed the issues cause and also the solution. For documentation purpose I'll write a summary of it here. Details will be available in the related PR.
Technically the behavior of the dApp here is correct (Talel hates me for this statement :joy: ). Nevertheless from a user perspective this is wrong and might be confusing. The origin of this issue is that the above display route is not a route on its own, but it is in fact the transfer route. So the title is correctly displayed. But the transfer route has a special case when the user has no token with a channel and behaves completely different then.
Fixing the symptom only isn't a good approach and actually very hard to do. Rather fixing "awkward" transfer route solves the issue at its root. Therefore the now split transfer route gets actually split into two routes. One as the usual transfer route that gets shown in most cases (in fact expect the first time). But in case the user has no connected token, the other route should be shown. This will be handled with a route guard. As our architecture for route guards is very powerful, modular and generic, this is a very nice use-case that is easy to add. Once the user has opened his first channel, the user will just see the regular transfer route.
