### ISSUE TITLE
Offset `settle` calls from channel partners

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2798]
When closing a channel and reaching the end of the settlement window, both channel partners will send a settlement transaction to the blockchain.

As those coincide, only one will go through, while one will be rejected. This could be observed while running the BF1 scenario.

- Successful tx: https://etherscan.io/tx/0x08d7125341f12b114d128271f9b37cc4645d825656bee8dc284655e88c083e8b
- Failed tx: https://etherscan.io/tx/0x55ac81644439c97447b8bd10c67f6c616e1fdfe6f2ee8c8e46e80739e171eaff

To limit failing transaction we could offset the transactions ending by the partner with the higher address by a number of blocks.

**Comment by palango** [comment]
On what criterion should the decision of who settles first be based?

- smaller/higher node address would penalize nodes with lower/higher addresses
- some `channel_id % 2` to calculate which node is first

Any other ideas?

**Comment by andrevmatos** [comment]
I'd propose to delay auto-settle if:
- partner is a PC (e.g. by checking it has `Delivery` capability); OR
- partner is the closing side

The first point is because PC always try to auto-settle early; the 2nd will have LCs _agreeing_ on giving priority to the closing side to settle, since usually they're the ones most/first interested in getting their funds back. The delaying side could still try to auto-settle in e.g. `revealTimeout` blocks after, if the channel wasn't settled by then.
