### ISSUE TITLE
Create protocol for manual testing

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2829]
## Description

It would be good to have some sort of checklist for our manual testing that is followed whenever someone takes on more extensive testing.

Having something similar as the one used for mainnet as standard to aid anyone who is conducting testing and to keep some sort of document on when/what was tested.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by agatsoh** [comment]
Steps to be followed before testing almost anything
1. Mention the commit hash or major minor release number to see which point in history have you tested.
2. The build steps whether followed or not
   * `yarn install`
   * `yarn workspace raiden-ts run build`
3. Whether raiden-dapp built or directly served
   * Build the raiden-dapp `yarn build` or `yarn build --mode modename` default is production
     log the contents of the .env.modename file by which you built the raiden-dapp
   * `npx serve -l 8080 ./dist`
   or
   * `yarn workspace raiden-dapp run serve`
 
Just initial thoughts will keep expanding on this.

**Comment by agatsoh** [comment]
Opening a channel:
Mostly channel is opened with a hub like node and not with a browser node though mediating could be enabled from there:
1. Node that channel is opened with is a hub and CLI node 
2. Required amount of SVT/RDN tokens are present in the main account for channel opening
3. if opening a channel from a CLI node note down the API call used to open the channel
https://raiden-network.readthedocs.io/en/stable/rest_api.html#put--api-(version)-channels
4. If opening the channel from browser node note down the subkey account because channel is opened with the subkey account.

Sending transfers:
1. Node has substantial amount of TTT/DAI or test tokens minted or acquired on mainnet
2. if sending payments from CLI node, note the API call for payments which was used to pay the target.
https://raiden-network.readthedocs.io/en/stable/rest_api.html#payments

**Comment by agatsoh** [comment]
Managing UDC
1. Note down the UDC contract address
2. Note down deposited tokens to the UDC
3. After aquiring SVT/RDN tokens deposit to the UDC by calling the API, note the API call. Check whether the response is as expected.
https://raiden-network.readthedocs.io/en/stable/rest_api.html#user-deposit

**Comment by agatsoh** [comment]
According to further discussions with @taleldayekh  we have come up with this sheet
https://docs.google.com/spreadsheets/d/1Dn_qm49TTBvAwvMZOuvkBmsCpz7vpdep2QCYrM3XwDk/edit?usp=sharing
Hence closing
