### ISSUE TITLE
I want to see how many tokens I can deposit

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#299]
## User story
As Chris I want to see how many tokens I can deposit so that I don't have to type a number first.

## Orginal description

After connecting to Hub (0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6) it doesn't show how much WETH I have available to open a channel, it only shows available WETH once I've typed in a number.

## Acceptance criteria
- 

## Tasks
- [ ] 

CC @MrCleanerPickerUpper

**Comment by christianbrb** [comment]
Update the description and title

**Comment by taleldayekh** [comment]
**Current Token Flow**
The home screen as it is implemented now displays all the user's connected token in one continuous list.

**New Token Flow**
The home screen should only display the user's current selected token together with its balance and all channels within its token network.

By displaying the channels for the token the user can easily get an overview of all the (open/closed/settled) channels as well as how many tokens have been deposited in respecitve channel.

A dropdown will reveal a list of all the user's connected tokens and the option to add a new token. If the user chooses another already connected token the user will be taken back to the home screen which will display this new token instead of the previous token.

![Issue #299](https://user-images.githubusercontent.com/43838780/66830222-3b708800-ef55-11e9-80f6-b9bd5a80dc0c.jpg)

**Comment by christianbrb** [comment]
That's consistent throughout the dApp and in my opinion, a nice option to not clutter the screen. Therefore I am closing it.

@MrCleanerPickerUpper Thanks again for your feedback :)
