### ISSUE TITLE
PFS's `ServiceRegistry.hasValidRegistration` is not verified

### ISSUE THREAD

**Issue by ezdac** [raiden-network/light-client#3001]
## Description

The node will only query the URL registered on-chain for a given PFS address but doesn't verify `ServiceRegistry.hasValidRegistration` for that address.
If that PFS did register in the past, but the registration expired, the contract will still return the URL.

In that case the node thinks that the PFS is functioning properly, but the transport server will not forward TO-DEVICE
messages to that PFS, since the transport server requires the service to have a valid registration in order to being whitelisted.

https://github.com/raiden-network/light-client/blob/b51dff44e492e757992ce72171ef76cab7621984/raiden-ts/src/services/utils.ts#L46-L53

## Acceptance criteria
- `hasValidRegistration` is polled on initialisation time
- eventually the expiry is memorised and the service disregarded on runtime at the expiry time.
- then a new PFS is used, or a warning emitted to the user if no other PFS could (should) be found

**Comment by andrevmatos** [comment]
We do this check on the `auto` fetched list of services, and those are usually the ones the user will use and pick:
https://github.com/raiden-network/light-client/blob/b51dff44e492e757992ce72171ef76cab7621984/raiden-ts/src/services/epics/pathfinding.ts#L278-L289

The only way the user could call with an invalid/expired service here was if it was explicitly set in CLI/config, and we wanted to do as the user asked on this case, and leave these validations to them (since specifying it explicitly is an advanced option). But if the matrix server not forwarding the presence events would mean this couldn't work, this may be an issue.

**Comment by ezdac** [comment]
Oh, I didn't notice the manual `valid_till` check.

> But if the matrix server not forwarding the presence events would mean this couldn't work

Maybe a custom, private PFS that does not depend on the matrix-multicast for graph-updates could be useful ... that's the only usecase I can imagine.

Otherwise, technically you could use the pfs without pushing updates to it - but if the pfs isn't registered, no-one can push updates to it if they don't control a custom matrix-server without the whitelisting. This means the pfs can't be functional in the expected way anyways.

I'd say at least go for a big red warning, occuring frequently like the RDN-threshold warning in the python client
