### ISSUE TITLE
Opening channel fails on Ropsten

### ISSUE THREAD

**Issue by pepae** [raiden-network/light-client#301]
## Description

Tried opening a W-ETH channel to 0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6 and failed on the setTotalDeposit function https://ropsten.etherscan.io/tx/0x63bf0f635f41c3f408c74c49e0712f5bc36d63a87c9c34d4696b9059ceb7cb9e
using metamask.

**Comment by kelsos** [comment]
So the reason for the failure is pretty simple. Since currently we only supported the `Red Eyes` contracts with the limits in place. The deposit is too big. According to the `Red Eyes` release blogpost, the max deposit is 0.15 ETH/WETH per channel. 

From etherscan, it seems that the amount deposited was 0.5 WETH. 

We are currently in the process of upgrading to the newer contracts. As far as I am aware of, the newer contracts set the limits during deployment. If the deposit limit is accessible when interacting with the contract, it would be better to actually check the limit before going onchain and fail earlier.

**Comment by pepae** [comment]
Sorry, my bad, tried with a lower amount and depositing worked, thank you!
