### ISSUE TITLE
dApp - notification card confirmation counter for Arbitrum

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#3036]
## Description

Notifications which are related to a on-chain transaction include a property at which block they become confirmed. This results into a visual counter that counts down for each block we see.
This behavior must/will change for roll-ups like Arbitrum. The question is how.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by weilbith** [comment]
This might be a no-brainer. The current implementation basically disabled the counter if the SDK configuration has a confirmation block counter of `0` or `undefined`. This value gets injected by listening to configuration update events emitted by the SDK. So if the SDK will just set this to either of the both values, we don't need to do anything here. Maybe test it once...

**Comment by weilbith** [comment]
@andrevmatos what are your plans how to handle this configuration property?

**Comment by andrevmatos** [comment]
My idea is to probably set `confirmationBlocks` to `1` by default for Arbitrum networks. I'd prefer to not have it as `0`, because we use this value to multiply and set certain margins and thresholds, if it'd be 0 this could cause not enough time to react on these things. 1 should be feasible though. The dApp doesn't need to do anything special here. The config will be set in the SDK, and blockNumber will be broadcast as usual, so dialog should still workfine. This is more of a security margin anyway, so even if this was not strictly needed (because of instant finality) it's still ok to have some confirmation in place.

**Comment by weilbith** [comment]
Hmm. But this literally states that we wait for 1 block to confirm events like open channel or so. Right?

**Comment by andrevmatos** [comment]
Hmm, yes, you're right. It's not probable, but possible, yes. I'll check everywhere we use `confirmationBlocks`, and ensure it works fine with `0` as well, let's aim for that on Arbitrum (instant finality).

**Comment by andrevmatos** [comment]
Done in #3034 
That PR may not get merged to `master` for now and stay in its own `arbitrum` branch, therefore I'll close this as implemented
