### ISSUE TITLE
CI/CD or git pre-commit hook should prevent linting errors

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#309]
## Description
At the moment we have `npm run lint` scripts set up within `raiden-ts` and `raiden-dapp`, but don't make use of them. As a result, we have different formatting in certain files and running `npm run lint` results in uncommitted changes.

It should be investigated whether it makes sense to

1. Integrate lint stages into CI/CD for `raiden-ts` and `raiden-dapp`
2. Create pre-commit hooks that prevent commits if there're linting errors. This might be difficult since we have a monorepo structure and no `package.json` in our project root. This would result in the latest registered pre-commit hook always overwriting the previously registered pre commit hooks

## Acceptance criteria
- Code in `master` is linted

## Tasks
- [ ] Use `--max-warnings=0` so CI/CD fails if there're linting errors

**Comment by andrevmatos** [comment]
Weird. Currently, they're used in CI:
https://github.com/raiden-network/light-client/blob/c0d53cecfcda8a4cafdbb87bc59dedb161d670f6/.circleci/config.yml#L68-L80
And it doesn't change the files, just check and exit with error if there's linting errors. On SDK, you'd need to run it as `npm run lint --fix` to fix the fixable errors, and `npm run lint` instead of `npm run lint:check` on the dApp to have uncommited changes. Am I missing something?

**Comment by nephix** [comment]
I think the issue in `raiden-dapp` is that with `npm run lint:check` linting errors get reported as warnings, not errors. Thus, circleci never fails

**Comment by kelsos** [comment]
So @vue/recommended are treated as warnings. This results to the lint checking passing since there are no errors. However from my prespective the vue recommented should be errors and CI should fail if the code is not properly linted. 

I would argue against pre-commit-hooks, my experience so far is that it makes everything slower. I don't know if a pre-push hook is possible, that might actually would be better. I don't really care about intermediate commits being 100% lint perfect but the HEAD should always be properly formatted.

**Comment by nephix** [comment]
Pre-commit and pre-push hooks are both possible with `husky` to set up, just our monorepo structure isn't very well suited for this. I think the performance can be neglected as our code base is quite small.

Easiest way would be to have CI/CD treat warning as errors
Best way would be to have `@vue/recommended` to throw errors instead of warnings IMO

**Comment by kelsos** [comment]
I would happy with having recommended throw errors instead too.

**Comment by andrevmatos** [comment]
`--max-warnings=0` option added to `eslint` command on `lint:check` will ensure script returns an error exit code if there're any warnings

**Comment by nephix** [comment]
We already found `--max-warnings=0` with @kelsos but it sounds more like a workaround solution, which could be sufficient.

I would prefer pre-commit/push hooks if `raiden-dapp` and `raiden-ts` would be separate repos.

**Comment by kelsos** [comment]
@nephix I would prefer to go with the `--max-warnings` approach to be honest. After trying to work with pre-commit hooks I found it cumbersome. I wouldn't mind using a pre-push as I mentioned before, but I wouldn't go splitting the repositories just for the hooks. 

Since the dApp acts as an example om how to use the SDK I would prefer for them to be in the same repo.

**Comment by andrevmatos** [comment]
Not only act as an example, but having both on the same repo makes it way easier to do "atomic PRs", which introduce breaking changes and can be synced in the same PR on both sdk and dapp. old raiden-libs was a very good example on how separate repos which happen to need to work together closely on a fast development pace is a pain to manage and get anything done.
I'd then argue splitting the repo at least before milestone 2 is hardly an option, and IMHO CI simply feels like a more fitting place for this than hooks.

**Comment by nephix** [comment]
Ok I have updated the task list.

**Comment by nephix** [comment]
Fixed for dapp in #335
