### ISSUE TITLE
Short quick start guide for testing the Light Client dApp

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#319]
## Description

Currently, it is not documented how to test the light client dApp. @MrCleanerPickerUpper and @BOR4 described [a nice way how to test the light client](https://www.reddit.com/r/raidennetwork/comments/cxtk7r/raiden_light_client_sdk_and_dapp_release_testnet/eynbltz?utm_source=share&utm_medium=web2x). We want to build on top of this guide a short quick start guide for every user who wants to test the Light Client dApp.

## Acceptance criteria
- There is one way described how get started with the Light Client dApp
- The guide is short and simple
- The guide is integrated in the main readme

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
A short quick start guide has been added and merged to the readme in the Light Client repo. I will close this issue.

**Comment by mat7ias** [comment]
@taleldayekh Tried to leave a comment on this a few days ago although I hadn't realized it was on pending: 

![Screenshot from 2019-09-09 20-48-02](https://user-images.githubusercontent.com/35585644/64525243-bdacd180-d343-11e9-9cf9-bae6d02cf2ec.png)

This week I've been moving away from using Infura and towards syncing Ethereum nodes instead. Having made the decision to not sync Ropsten since then, the Raiden node 0x5257...840D6 (ENS: mat7ias.eth) now runs on Goerli. I feel it'll be better listing ENS(+network), rather than the specific address. It allows the owner of the node the flexibility of not having to submit a PR if the address changes whilst ownership stays the same.

**Comment by taleldayekh** [comment]
Hi @mat7ias, let me see if I understand you correctly. The address 0x5257...840D6 works on Goerli now and not on Ropsten? So I should update the step-by-step guide to acquire and wrap Gö-ETH instead?

**Comment by mat7ias** [comment]
I never had the Ropsten chain synced. The address was only interacting with Ropsten via Infura RPC prior to today when I finished syncing the Goerli chain to use as a reliable alternative.
Your guide wouldn't work the same on Goerli since wrapped Gö-ETH isn't a registered token network on Raiden (production mode) Goerli and it can't be registered due to the token restrictions (TTT is the registered token on Goerli). Might change once Alderaan is out? Although for the guide to stay similar 0x would need to support Goerli so you can use it to wrap, which I believe it doesn't yet.
Since the guide has already been created, I'll try sync the Ropsten chain instead to let the guide stay the same until Alderaan.

**Comment by taleldayekh** [comment]
Ah, ok, I see, thanks a lot for the explanation and for the effort of syncing Ropsten. :)
