### ISSUE TITLE
Mediated transfer hangs, if no channel is available

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#377]
## Steps to Reproduce

1. Trying a mediated transfer 
`0xB84C6bFBA1108543Ea47e8B9a669CB39ffc70f6A` -> `0x456e2459b6E01FF30375D59f24d359655bEB6754` -> `0x691A2E94E4A2b6178db98b92Ea13E9ddE1695CC8` 

2. There is no channel between 
`0x456e2459b6E01FF30375D59f24d359655bEB6754` and `0x691A2E94E4A2b6178db98b92Ea13E9ddE1695CC8` 

## Expected Result

- Transfer fails

## Actual Result

-  After 
```
action transferSecret @ 13:18:20.926
action transferSigned @ 13:18:20.931
```
it hangs

```
action messageSend @ 13:18:25.196
client.js:2057 sendEvent of type m.room.message in !HjkFjChsWWfHIzZuAE:transport03.raiden.network with txnId m1570533505201.78
client.js:2248 Event sent to !HjkFjChsWWfHIzZuAE:transport03.raiden.network with event id $wDx3CLfNd0eY1PlJBRUakUn4_8Lo4VTC1xzLZTtg7Ls
setting pendingEvent status to sent in !HjkFjChsWWfHIzZuAE:transport03.raiden.network
```

```
action messageSent @ 13:18:25.345
sync.js:89 Already have event $wDx3CLfNd0eY1PlJBRUakUn4_8Lo4VTC1xzLZTtg7Ls in limited sync - not resetting
```

**Comment by andrevmatos** [comment]
If the transfer was signed, it somehow DID found a path to your target. Mayb not the direct channel, but some other. If you have looked above, you would have seen a `pathFound` action emitted which contained the route used. It's also stored in state in the `sent[secrethash].transfer[1].metadata.routes` field. Since it did found a route (through PFS), it's not hanging, but waiting for the rest of the protocol. If it's not continuing, it's on the mediation/target side, not on the LC. It'll eventually expire the transfer if they don't respond as expected on time.

**Comment by christianbrb** [comment]
Closing in favor of
#168 
#172 
#426
