### ISSUE TITLE
Matrix resync / health check to avoid deleting the local data

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#381]
## Description

Currently, the local matrix data needs to be deleted, if a transfer hangs (see eg https://github.com/raiden-network/light-client/issues/373)

We need to find a way how to deal with Matrix communication layer failures without the need to manually delete the data.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
I'd say this issue and related are not only about resync/realthcheck, but also or mainly about being able to retry authenticating on other available transport servers if the previous one fails.
This is easily done with our reactive architecture: on `initMatrixEpic`, after sorting the servers by RTT, instead of just choosing one and proceeding with it, we may do a FIFO queue/cicle of servers, and try to login and healthcheck on each, retry on next if first fail and pick the first which succeeds.
Later on, when aiming at more longer running instances (full client, milestone 2), this can even be expanded to allow full transport server reinstantiation/switch at runtime in case of transport exceptions, transparently.

**Comment by christianbrb** [comment]
Sounds great :-)

**Comment by christianbrb** [comment]
Not reproducible at the moment
