### ISSUE TITLE
Set Total Deposit fails

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#400]
## Steps to Reproduce
1. Connect to https://lightclient.raiden.network/channels/0x3ed0DaEDC3217615bde34FEDd023bC81ae49251B on Goerli
2. Deposit 0.000000000000000021 in the channel to 0x456e2459b6E01FF30375D59f24d359655bEB6754
3. The first transaction is successful (see https://goerli.etherscan.io/tx/0x642c10aa82db5ced1d1a20a6d389c1ad9db3d681613bff2a555c18d68fc137f1)

## Expected Result
- The second transaction is successful and there are more tokens deposited to the channel

## Actual Result
- The second transaction (Set Total Deposit) fails (see https://goerli.etherscan.io/tx/0xc82ed9771ab83c64fe5bed84b47f278f4752812192473a7a7e723e8cc23f5971)

**Comment by christianbrb** [comment]
Set Total Deposit when opening a channel to a new hub (0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6) workded

**Comment by kelsos** [comment]
@christianbrb here are the findings of my investigation.

While it was not easy because I needed an archive node in order to debug the reverted transaction, we are lucky because it is easy to sync a new Goerli archive node :D

After that, I used [Remix](https://remix.ethereum.org/) to debug the failing transaction and I found out that the transaction reverts at the following line:

https://github.com/raiden-network/raiden-contracts/blob/a8af89a663770d6cf4312017c684293f8b144e91/raiden_contracts/data/source/raiden/TokenNetwork.sol#L349

The two failing transactions attempted to set the total deposit to:

## Transaction 1
[0x7aa280944857eeed6d8005cc3104ce3c33ec482a5c52fa11e0378328ee86d7e1](https://goerli.etherscan.io/tx/0x7aa280944857eeed6d8005cc3104ce3c33ec482a5c52fa11e0378328ee86d7e1)@`1490832`

```
Function: setTotalDeposit(uint256 channel_identifier, address participant, uint256 total_deposit, address partner) ***

MethodID: 0x63ea0143
[0]:  0000000000000000000000000000000000000000000000000000000000000024
[1]:  000000000000000000000000b84c6bfba1108543ea47e8b9a669cb39ffc70f6a
[2]:  0000000000000000000000000000000000000000000000000000000000000064
[3]:  000000000000000000000000456e2459b6e01ff30375d59f24d359655beb6754
```

This attempts to set the total deposit to `100`.

## Transaction 2
[0xc82ed9771ab83c64fe5bed84b47f278f4752812192473a7a7e723e8cc23f5971](https://goerli.etherscan.io/tx/0xc82ed9771ab83c64fe5bed84b47f278f4752812192473a7a7e723e8cc23f5971)@`1490884` 

```
Function: setTotalDeposit(uint256 channel_identifier, address participant, uint256 total_deposit, address partner) ***

MethodID: 0x63ea0143
[0]:  0000000000000000000000000000000000000000000000000000000000000024
[1]:  000000000000000000000000b84c6bfba1108543ea47e8b9a669cb39ffc70f6a
[2]:  0000000000000000000000000000000000000000000000000000000000000015
[3]:  000000000000000000000000456e2459b6e01ff30375d59f24d359655beb6754
```

This attempts to set the total deposit to `21`.

## Successfult Calls

We can see from the fire events that `0xB84C6bFBA1108543Ea47e8B9a669CB39ffc70f6A` managed to call `setTotalDeposit` twice before with bigger values.

```json
[
  {
    "channel_identifier": 36,
    "participant": "0xB84C6bFBA1108543Ea47e8B9a669CB39ffc70f6A",
    "total_deposit": 10000000000000000,
    "block": 1433941
  },
  {
    "channel_identifier": 36,
    "participant": "0xB84C6bFBA1108543Ea47e8B9a669CB39ffc70f6A",
    "total_deposit": 20000000000000000,
    "block": 1434298
  }
]
```

When setting `total_deposit` we always do it based on the previous `total_deposit`. For example if I have a total deposit of `10000000000000000` wei and I want to add another `100` I will call `setTotalDeposit` with a `total_deposit` `10000000000000100`.

@andrevmatos based on the discussion we had yesterday it seems that somehow the previous events where missed.

**Comment by christianbrb** [comment]
Try to reproduce
1. Deposit small amounts
2. Close the browser
3. After a while reopen and check, if it has been properly picked

**Comment by christianbrb** [comment]
Tried to reproduce it and I was running a new issue https://github.com/raiden-network/light-client/issues/484 (maybe the same root cause?)

**Comment by christianbrb** [comment]
Next try:
- Making a deposit
- Signing "Approve"
- Closing the browser while "Depositing Tokens"
- Didn't work: https://goerli.etherscan.io/tx/0x88dad24b14e883accacfce46b2bc697ad3577101b2f78ada4c457bbe00646e2e

Next try:
- Making a deposit
- Signing "Approve"
- Signing "Set total deposit"
- Closing the browser
- Reopening the browser
- Worked (Total deposit is now higher)
- I get a signing message out of nowhere (#401)

**Comment by christianbrb** [comment]
Ok, but the root cause of the issue does not seem to happen any more. Closing
