### ISSUE TITLE
Extend try out guide with clean state

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#410]
## Description
In case of an update or unrecoverable crash the state of the dApp/SDK needs to be cleaned. A potential tester might not be aware of this action.

## Acceptance criteria
- The user knows when to do this
- The user knows how to do it for different browsers
- We rely on external sources rather than describing it in detail in our readme

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
I'd be careful with this. We SHOULDN'T tell the users to clean up state. This breaks a ton of assumptions about protocol sync between clients. It's actually only safe to be done if no payment was performed or one controls and cleans up also the state of the full clients, which by its turn only works if one controls all node with which channels are opened.
SDK state is atomic. It never gets inconsistent even over unrecoverable crashes, so there's no need to clean ever because of this.
On updates, we may change the schema, which may make the dApp not load with old state. But IMO, more important than this I'd say is to provide migration functions for the state upon changes on the schema than to need to tell the user to clean state.

**Comment by christianbrb** [comment]
Refinement:
- We should not do that
- We need to stay in sync with the partner
- Potential solution: Migrate the data from one version to the other (new issue)
- Matrix out of sync #130 
- Closing this issue
