### ISSUE TITLE
Channel Management

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#571]
## Description
Container to collect ideas, screen flows, etc. for an improved channel management

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
**Roy's mockups for channel management proposal**

All channels for a selected token are visualised as cards. The user shifts between channels by swiping through the cards.

Underneath is a list with the transaction history for the coresponding channel. Similar to what is currently being discussed in issue #426 .

A main menu is added (the + button in the bottom)
![tokens-channels-1](https://user-images.githubusercontent.com/43838780/69340973-f254d780-0c68-11ea-9990-515b2d781bf2.jpg)

The user can "flip" each card (channel) and access options for closing and settling the channel.
![tokens-channels-2](https://user-images.githubusercontent.com/43838780/69341305-9cccfa80-0c69-11ea-9ea5-815cbebae052.jpg)

The user performs payments and deposits by accessing those options from the main menu.
![tokens-channels-4](https://user-images.githubusercontent.com/43838780/69341590-254b9b00-0c6a-11ea-92a8-4c502c3bee92.jpg)

**Comment by christianbrb** [comment]
@taleldayekh and @christianbrb 

### Proposal:
First step towards the card design. Channels can be shifted left and right.

![grafik](https://user-images.githubusercontent.com/35398162/69524766-19602180-0f67-11ea-923f-85e02ed102bb.png)

### Questions:
- Do we want to keep the automatic selection of the channel with the highest capacity?
    - We think it is nicer, if the channel
- What is the capacity above „TestToken“ on the top?
    - If it is the total capacity of all channels we keep it

**Comment by andrevmatos** [comment]
Currently, the channel actually used for transfer is either direct channel (if available) or the one informed by PFS, which can then be selected as per the available routes.
The auto selection is only to show relevant capacity. We need to show a single one, because there's no point into summing them if you can't make a single transfer that big, so we show the highest one which is the one with highest capacity and chance of being picked by PFS.
Notice we didn't put much effort into improving on this because usually it shouldn't matter much, as we expect the common case to be a single channel per token network, so it's the same used for capacity above and the only one pickable by PFS.

**Comment by nephix** [comment]
> The user can "flip" each card (channel) and access options for closing and settling the channel.

What are steps in the UI to close/settle a channel from the slider?

**Comment by taleldayekh** [comment]
If we, as a first step, only are moving the current channels to the transfer view then perhaps the best is to keep the close/settle as it is in the dropdown for each channel.

**Comment by christianbrb** [comment]
Good collection an discussion, but not actionable. Closing.
