### ISSUE TITLE
Create a changelog

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#643]
## Description
Start creating a change log

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
I've seen some tools which automate it through squashed PRs and closed bugs with proper labels. I'd prefer it as it dimishes the chances of missing something, although if not pretty/good enough, we could always go with tools to help manual changelog keeping.

**Comment by kelsos** [comment]
I am not still sure that the effort of keeping everything the way the automated tools require, in order to generate a proper changelog would be less than doing it manually.

In both Raiden and the WebUI, the changelog is updated by hand, on every PR that contains changes that should go to the changelog. Especially the WebUI follows this [keepchangelog](https://keepachangelog.com/en/1.0.0/) format. 

You can see the WebUI changelog [here](https://github.com/raiden-network/webui/blob/master/CHANGELOG.md). The best thing about this format is that it is already markdown so it's easy to move it to the GitHub release without major modifications if any.

Also, another question is do we also keep a separate log for the dApp on the `raiden-dapp` subdirectory? Would that make sense?

@andrevmatos @nephix what do you think about the `keepchangelog` format. The idea is to update the entries in the PR that adds or fixes or closes anything. Or are you more in favor of using labels and better issue descriptions to automate the process?

**Comment by nephix** [comment]
I have no real opinion on this. In the past we have done both, 100% automating and manually creating and neither worked satisfactory.

> The idea is to update the entries in the PR that adds or fixes or closes anything

Can you give an example what this would consist of?

I think 
1. Squashing PRs with meaningful titles ("Fixes...", "Adds new...", "Refactored...")
2. Generating a markdown draft via git log between two tags on master
3. Filter dependabot PRs
3. Categorize the list manually into bugs, features, etc

should™ work
