### ISSUE TITLE
Rework Error Messages

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#699]
## Description
The error messages need to be reworked

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Is this still the case?

**Comment by weilbith** [comment]
I'm sorry this issue is older then I'm part of the team. The description isn't giving much information and I could not match if with something I'm aware of. Sorry. :speak_no_evil:

**Comment by christianbrb** [comment]
@weilbith Don't worry :) I have been asking you because I have remembered, that you were working on CLI/API errors.
 
Let's wait for @andrevmatos :)

**Comment by weilbith** [comment]
Yes, but I see a big difference there. The CLI was meant to be as dump as possible, acting as a flat gate to the SDK. Therefore we decided that the SDK should do more sensitive validation of the users input parameters. The most smart thing the CLI does then is to categories the different errors to assign them to a certain HTTPS status code. So after all we talk about machine-to-machine communication here. The clients should make sure they use correct (formatted) inputs.
On the dApp side we should not rely on the SDKs parameter validation and forward its error messages. It would be a horrible user experience, since it would be slow, not precise enough and would be more a try-and-error approach rather then a interactively supportive approach.

But after all I recognize that I discussesd about parameter validation in first place. Of course this a way wider topic. So waiting for Andre :grimacing:

**Comment by andrevmatos** [comment]
I don't have anything strong to say: @weilbith already gave a good explanation about it. Error messages can ALWAYS be reworked to be more explicit, informative and whatnot, but I'm happy with the current state of it. It'd be more UX, if something isn't good enough for dApp, than actual errors, as we're already quite covered on this matter. Afterall errors aren't something we expect often if things are happy, if they're not, for the logic, we mostly only care if there's an error, the message itself only matters for the users.

**Comment by christianbrb** [comment]
Example:

![grafik](https://user-images.githubusercontent.com/35398162/89278517-82477f80-d646-11ea-8057-354503899be3.png)

**Comment by taleldayekh** [comment]
Closing, we create separate issues for theses kind of error messages when they appear.
