### ISSUE TITLE
dApp does not work in brave browser

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#742]
Disclaimer: I'm not sure if brave browser is supported, or if it's a bug in brave's forked meta mask implementation

## Steps to Reproduce
1. Download Brave from https://brave.com
2. Start brave
3. Click hamburger -> Crypto Wallets
4. Create wallet and select Goerli test net
5. Go to https://lightclient.raiden.network
6. Click connect

## Expected Result
- dApp launches

## Actual Result
No progress, only loading spinner on connect btn:
![Screenshot 2019-12-13 at 10 01 30](https://user-images.githubusercontent.com/3169205/70787933-13a07380-1d90-11ea-99da-97f3553b5a0a.png)

## Additional Infos (Optional) 
- Browser & version: Brave Version 1.1.20 Chromium: 79.0.3945.74 (Official Build) (64-bit)
- Browser console errors: see screenshot
- Device / OS: macos

## Acceptance Criteria
*

**Comment by kelsos** [comment]
@nephix I investigated this on Linux, and there is definitely something going on with brave. 

If the Crypto Wallet page is open in a tab and you press connect on the light client it doesn't show a popup notification but instead shows the confirmation for any signature inside the crypto wallet page.

In order to see the notification, the crypto wallet tab has to be completely closed. Can you verify if that was the issue you encountered or not?

![image](https://user-images.githubusercontent.com/2269732/72013703-b0a2df00-325e-11ea-8016-f32912390b7a.png)

**Comment by nephix** [comment]
As far as I remember, I didn't have the wallet tab open and just clicked connect in the Light Client, expecting some kind of notification pop up but nothing showed up.

I will try it again with notification page opened up.

**Comment by nephix** [comment]
I updated Brave and tried again (macOS) and I got a MetaMask popup (or their implementation of it) and the light client shows the home screen after clicking on connect

**Comment by kelsos** [comment]
Yes, metamask on brave behaves a bit weirdly but we can safely assume that this issue was not on a dApp issue. Do you think it needs further investigation or can we safely close this issue now?

**Comment by nephix** [comment]
No can be closed, it was probably an issue in Brave 👍
