### ISSUE TITLE
Use filters and lazy members loading to optimize matrix syncing

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#746]
## Description

Although our usage of Matrix is already quite optimized through `matrix-js-sdk` state keeping, busy/crowded rooms like `discovery` and `path_finding` may include quite a sizeable state and number of events we don't really care for.

Matrix specification includes support for [filters](https://matrix.org/docs/spec/client_server/r0.6.0#api-endpoints) and [lazy members loading](https://matrix.org/docs/spec/client_server/r0.6.0#lazy-loading-room-members), to allow reducing the size of the sync payload needed to both perform initial syncing and delta updates.
We should make use of it to avoid syncing any state and events possible from these rooms.

Initial/first fetching of users/presences isn't a problem, as it uses `search_user_directory` functionality, which doesn't require room state. But later presence events needs to be investigated, as while they're not specific to a room, they are only sent for "users of interest", which are mainly "co-members" in rooms, so we need to check if filtering out events for these rooms could impact our ability to receive global presence events for users on these rooms as well.

## Acceptance criteria
- State and events from global rooms aren't ever fetched
- State and events from other rooms do
- We don't lose presence events from co-members in the global rooms

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
For reference: right now, the initial `sync` request downloads around **7.8MB** of data, mostly state for the global rooms above. This is quite a sizeable amount of data which isn't really needed.

**Comment by andrevmatos** [comment]
Raiden-py implementation: https://github.com/raiden-network/raiden/pull/5571
May be useful for us to piggyback on the implementation.
We just need to be careful, that this needs to be set **before** initial sync, or else it'll still download this ton of useless data
https://github.com/raiden-network/light-client/blob/1299893b37f905f25fcc933c43b343d6710c14f5/raiden-ts/src/transport/epics.ts#L436
May also require extending a little our typings of matrix, if it's not there yet.

**Comment by kelsos** [comment]
So after fixing my typo on the filter the presences in the API work properly and I can see the responses containing presence updates. However, there is an error.

```javascript
Error validating presence event, ignoring Error: "invalid hexidecimal string (arg="value", value="@0x504300c525cbe91adb3fe0944fe1f56f5162c75c:transport04.raiden.network", version=4.0.42)"
    throwError errors.js:76
    arrayify bytes.js:53
    splitSignature bytes.js:248
    recoverPublicKey secp256k1.js:88
    recoverAddress secp256k1.js:94
    verifyMessage secp256k1.js:98
    matrixPresenceUpdateEpic epics.ts:679
    RxJS 3
```

When a user is created in the matrix js SDK the display name is initially set to the user id.
https://github.com/matrix-org/matrix-js-sdk/blob/04bbfae08e3e8fe9d329b2f950c4f86545a3cfea/src/models/user.js#L55

Then it gets tracked and the displayName gets updated.

https://github.com/matrix-org/matrix-js-sdk/blob/04bbfae08e3e8fe9d329b2f950c4f86545a3cfea/src/store/memory.js#L133

With the filter, we ignore anything other than presence updates for the broadcast rooms and this means that the users are not properly tracked anymore and they display names are not properly updated.

I am gonna modify the `matrixPresenceUpdateEpic` so that if the `userId` is equal to the `displayName` we manually use the search user directory to update the display name for that user.
