### ISSUE TITLE
Redirecting to Transfer screen displays blank screen during delay

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#748]
## Steps to Reproduce
1. Press the "Channels" link on the Transfer screen
2. In the channels overlay press the upper left back arrow

## Expected Result
Expecting the arrow to take me back to the Transfer screen

## Actual Result
Takes me to a blank screen
![bug](https://user-images.githubusercontent.com/43838780/70922506-7e6adc80-2026-11ea-93c5-c173f07a4e0d.jpg)

**Comment by taleldayekh** [comment]
I discovered just now that it redirects to the Transfer screen eventually, it just takes quiet some time.  If we can't do anything about the delay we should probably provide something indicating a loading process.

**Comment by christianbrb** [comment]
@taleldayekh Thanks for tracking your observations :)
We have got this issue to tackle the problem throughout the dApp -> https://github.com/raiden-network/light-client/issues/688

**Comment by taleldayekh** [comment]
Ah, yes, missed that we had that one. :)

**Comment by andrevmatos** [comment]
I investigated this. The delay wasn't caused by tokens loading, but was triggered on next action/event, indicating some watcher was waiting for any commit, i.e. wasn't fired at first, just on next event, which usually was a SDK's `newBlock` commit. Ended up being the `tokens` watcher in `Home.vue`.
One-liner fix is available in #830.
