### ISSUE TITLE
Token not shown on Select Token after disconnect

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#833]
## Steps to Reproduce
1. Connect to the TTT token on Goerli (https://goerli.etherscan.io/token/0x3ed0daedc3217615bde34fedd023bc81ae49251b)
2. Disconnect from TTT token
3. Open the dApp
4. Click on "Connect new token"
5. Search for TTT on Select Token screen

## Expected Result
- I am able to select the TTT Token with the address 0x3ed0daedc3217615bde34fedd023bc81ae49251b

## Actual Result
- I don't find any TTT Token 

## Acceptance Criteria
* Try and reproduce
* State backup

## Task
*

**Comment by christianbrb** [comment]
Cleared the application data and the token is back :)

@andrevmatos Maybe related to #834 ?

**Comment by nephix** [comment]
TTT's token address is now `0x31aA9D3E2bd38d22CA3Ae9be7aae1D518fe46043`. I remember I had similar behavior when I didn't sync the light client for a while and the address of a token network has changed

**Comment by kelsos** [comment]
@nephix like I mentioned in the https://github.com/raiden-network/light-client/pull/870#discussion_r365137792 the token being updated in the token registry cannot happen.

You can register a token, in the network registry but after the TokenNetwork is deployed you cannot do any modification. The symbol is not a unique identifier for the token, only the address is. I can have  multiple TTT tokens deployed within the same TokenNetworkRegistry with different addresses, they are not the same token, they are different tokens with the same symbol (the symbol and name are not unique). If there is only one entry of the TTT token in each different state this could mean that the TokenNetworkRegistry in the two states is different, which means that we actually have two different Smart Contract deployments (two different networks).

@andrevmatos what happens when the SDK and dApp go through a contract update? The dApp will get updated along with the SDK to use the newer contracts but it can't interact with the previous contracts and state and channels? how do we handle it?

**Comment by nephix** [comment]
That's kind of what I meant, I just couldn't get the wording right. Thanks for clarifying @kelsos

**Comment by nephix** [comment]
At the time this can't be reproduced with the provided steps and possible solutions for this need to be discussed

**Comment by andrevmatos** [comment]
The SDK's state localStorage key includes the Token Network Registry address in the name, which is the "identifier" for a network version/deployment. When it gets updated, the old state is kept there but are not accessed. For SDK, it's a new state/new account, which gets initialized, scanned, populated from scratch.
As kelsos said, token addresses doesn't change on a network. Only possibly a new one can be deployed/registered. I'm not sure how it could be an SDK issue. Could you reproduce it on the SDK?

**Comment by nephix** [comment]
Nobody said it's an SDK issue, it's a general issue that needs to be handled on a conceptual level I guess

**Comment by nephix** [comment]
I'm closing this in favor of #874

**Comment by christianbrb** [comment]
It was exactly the same token with the same address, which did not show up. It only showed up after I have cleared the application data.
