### ISSUE TITLE
dApp crashes during transfer

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#886]
## Steps to Reproduce
1. Navigate to the transfer screen
2. Do a mediated transfer (https://lightclient.raiden.network/transfer/0x31aA9D3E2bd38d22CA3Ae9be7aae1D518fe46043/0x2d1bC0F9e6B755155cB379546C1546E0353E6b19?amount=0.00000000000001)
3. Sign the first message

## Expected Result
- Sign the second message

## Actual Result
- dApp crashes and the connect screen is shown

## Additional Infos (Optional) 
Console log [lightclient.raiden.network-1579077531960.log](https://github.com/raiden-network/light-client/files/4063825/lightclient.raiden.network-1579077531960.log)

![grafik](https://user-images.githubusercontent.com/35398162/72418444-22a58780-377b-11ea-9574-be0f90c24901.png)
![grafik](https://user-images.githubusercontent.com/35398162/72418259-c9d5ef00-377a-11ea-9f57-34636c9e431a.png)

**Comment by kelsos** [comment]
It seems that a call to the transfer04 failed with 403 (forbidden). Was there anything else in the logs?

**Comment by christianbrb** [comment]
I have attached the logs (https://github.com/raiden-network/light-client/files/4063825/lightclient.raiden.network-1579077531960.log)

**Comment by andrevmatos** [comment]
This is very weird. The PFS warnings and errors are expected, as a lot of registered PFS aren't valid, and are just informative. The cause seems to indeed be that 403 from transport server, which shouldn't happen.
We need to document steps to enable logs for hosted instance, and require it on bug reports, as they're invaluable for understanding exactly where unexpected exceptions happened, but in this case, seems to be on `messageSend` of `Delivered`, which definitely shouldn't happen and could be some kind of server error.
Nonetheless, we must handle and retry this kind of exception, as it coud be just a temporary error.
